src/modules/BaElement.js
test/modules/BaElement.test.js

Call of `render() ` should be skipped  as long as element/component not is initialized

Prevent rendering before initialization is done

---

src/modules/contextMenue/store/contextMenue.action.js
src/modules/map/store/olMap.action.js
src/modules/menue/store/sidePanel.action.js
src/modules/modal/store/modal.action.js
src/modules/uiTheme/store/uiTheme.action.js

In order to have the action creators within the documentation, we use the `@module` annotation with a value conforming to the pattern `${moduleName}/action`.
Have a look @ the generated docs...

Improve documentation of action creators

---

src/modules/commons/components/toggle/Toggle.js
src/modules/header/components/Header.js
src/modules/uiTheme/components/toggle/ThemeToggle.js
test/modules/commons/components/Toggle.test.js
test/modules/uiTheme/components/toggle/ThemeToggle.test.js

It's now possible to register the callback by an event listener within the markup:
`<ba-toggle  @toggle=${onToggle}><span>Toggle me!</span></ba-toggle>`
Have also a look at our showroom...

Toggle element: make it possible to register the callback within the markup

---

src/modules/commons/components/button/Button.js

In order to re-render the view only when the state has actually changed, we have to compare new values with existing values
before we call `render()`.
This is a generic  recipe and valid for all components, which expose internal state via a setter method.

Prevent unnecessary re-rendering

---

src/modules/map/components/infoButton/assets/info-circle-solid.svg

The info icon seemed to be too small for the button, so that there was a white outline visible (thx to @taulinger for reporting). Was fixed by making the icon bigger with the viewBox attribute of the svg-tag. (Funnily width and height (of svg-tag) attribute had no impact on that icon.)

Fix info button

---

src/injection/core/injector.js
test/injection/core/moduleConfig.js
test/injection/core/moduleInjection.test.js

With that is is possible to register modules within the 'config.js' like that:
```
import { myModule } from '../some/package/';
$injector
.registerModule(myModule)
...
```

Add possibility to register modules for DI

---

package-lock.json
package.json
src/injection/config.js
src/modules/footer/components/mapInfo/MapInfo.js
src/services/OlCoordinateService.js
src/services/provider/proj4.provider.js
src/services/provider/stringifyCoords.provider.js
test/service/OlCoordinateService.test.js
test/service/provider/proj4.provider.test.js
test/service/provider/stringifyCoords.provider.test.js

Added custom SRS support.
The BvvProvider registers definitions for 25823 and 25833.
Example for using it in ol:
```
import { get } from 'ol/proj';
get('EPSG:25832') //just an example, later we will use the MapService to get the wanted id of the srs
```
Example of transforming a coordinate:
```
coordinateService.transform(coord25832, 25832, 25833);
```

Custom SRS management

---

src/services/MapService.js
src/services/provider/mapDefinitions.provider.js
test/service/MapService.test.js
test/service/provider/mapDefinitions.provider.test.js

`MapService#getSridDefinitionsForView` returns  `SridDefinition` objects, which contain a label

Rename mapservice method and include a "label" property

---

karma.conf.gha.js
package.json

`karma-coveralls plugin` isn't needed anymore

Remove karma-coveralls plugin

---

src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js

adding a private getter-method for snaptolerance depending on
environment information (isTouch) to deliver a better draw-behavior in
small areas on Desktop-Environments on the one hand and
better first-point or last-point snaps on Touch-Environments

add a switch for device related snapTolerance

---

src/modules/BaElement.js
src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
src/modules/map/store/layers.action.js
src/modules/map/store/layers.reducer.js
src/modules/map/store/measurement.observer.js
src/services/StoreService.js
src/utils/storeUtils.js
test/modules/map/components/olMap/OlMap.test.js
test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
test/modules/map/store/layers.reducer.test.js
test/modules/map/store/measurement.observer.test.js
test/utils/storeUtils.test.js

...independently from using a `BaElement` component.
For an example have a look at `measurement.observer.`.
An OlLayerHandler will register an observer for the store the same way . 
In this case, the store has to be injected from the `StoreService`.

Add possibiltiy to observe state changes of the store

---

package-lock.json
package.json
webpack.config.js

After recent upgrade of webpack-cli, auto-detection of an available port for the dev-server wasn't working anymore

Make port detection available again

---

src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js

add changeListener for measurement-layer to bind layer-visibility and opacity to overlay-visibility/opacity 
fix for #110
the current fix interpretes the measurement-layer as internal object (OlMeasurementHandler is stateful) and therefore using listeners to react on changes of the layer.
But... it breaks the design (use the StateStore as the single point of truth)...so a implementaion with a observer is more appropriate.

add changeListeners for measurement-layer

---

src/modules/BaElement.js
src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
src/modules/map/store/layers.action.js
src/modules/map/store/layers.reducer.js
src/modules/map/store/measurement.observer.js
src/services/StoreService.js
src/utils/storeUtils.js
test/modules/BaElement.test.js
test/modules/map/components/olMap/OlMap.test.js
test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
test/modules/map/store/layers.reducer.test.js
test/modules/map/store/measurement.observer.test.js
test/utils/storeUtils.test.js

... within a BaElement.
Example:
If the state of an element extracted from die global store looks like: 
`{ foo:bar, some:42 }`
...and we want to be notified about changes individually, we can now register an observer:
```
observe('foo', (value) => { console.log('foo changed: ' value) });
observe('some', (value) => { console.log('some changed: ' value)});
```

Add possibiltiy to observe discrete state changes

---

src/modules/footer/components/coordinateSelect/CoordinateSelect.js
src/modules/map/components/olMap/OlMap.js
src/modules/map/store/map.action.js
src/modules/map/store/map.reducer.js
src/modules/map/store/pointer.action.js
src/modules/map/store/pointer.reducer.js
src/modules/map/store/position.action.js
src/modules/map/store/position.reducer.js
src/services/StoreService.js
test/modules/footer/components/coordinateSelect/CoordinateSelect.test.js
test/modules/map/components/olMap/OlMap.test.js
test/modules/map/store/map.reducer.test.js
test/modules/map/store/pointer.reducer.test.js

Add 
1. a reducer for pointer based interactions of a user with the map
2. a reducer for interactions with the map on a higher abstraction level, like moving the map
So we are able now to
- switch off geolocation tracking when the user is dragging the map
- refactor the trigger mechanism of the context menu

Pointer and map reducer

---

src/modules/BaElement.js
test/modules/BaElement.test.js

BaElement#observe: warn only  on undefined values

---

test/service/OlCoordinateService.test.js

It does makes sense when a test for `transformExtent` also uses that method...

Fix wrong method call in CoordinateService test

---

src/modules/BaObserver.js
src/modules/map/store/ContextClickObserver.js
src/modules/map/store/GeolocationObserver.js
src/modules/map/store/LayersObserver.js
src/modules/map/store/MeasurementObserver.js
src/modules/map/store/PositionObserver.js
src/services/StoreService.js
test/modules/BaObserver.test.js
test/modules/map/store/ContextClickObserver.test.js
test/modules/map/store/GeolocationObserver.test.js
test/modules/map/store/LayersObserver.test.js
test/modules/map/store/MeasurementObserver.test.js
test/modules/map/store/PositionObserver.test.js
test/service/StoreService.test.js

Based on this changes it is possible to define a logical order during initialization of the app.
For example, the information about configured background layers should be loaded before the geoResources are actually
fetched from the backend.

Register observer asynchronously

---

src/modules/map/components/contextMenu/MapContextMenuContent.js
test/modules/map/components/contextMenu/MapContextMenuContent.test.js

The Product Owner wants another context menu content order, therefore the order of the context menu was reordered.

Change context menu content order

---

src/modules/map/components/olMap/handler/measure/GeometryUtils.js
src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
test/modules/map/components/olMap/handler/measure/GeometryUtils.test.js
test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js

The calculation of the partitionDeltas for a geometry is now based
on the given resolution ot the mapview, to prevent an overload of
partitionpoints in edge cases.
Add listener to the event 'change:resolution' of map.getView() to
refresh the overlays on zoom interactions while drawing

fix calculation and usage of partitionDeltas

---

src/injection/config.js
src/modules/map/components/olMap/handler/measure/GeometryUtils.js
src/modules/map/components/olMap/handler/measure/MeasurementOverlay.js
src/services/UnitsService.js
test/modules/map/components/olMap/handler/measure/GeometryUtils.test.js
test/modules/map/components/olMap/handler/measure/HelpTooltip.test.js
test/modules/map/components/olMap/handler/measure/MeasurementOverlay.test.js
test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
test/service/UnitsService.test.js

as enhancement and refactoring for two utility-methods, this PR introduce a service to format distance- and area-values with their respective unit.
This refactoring is needed for future implementations, where such values have to displayed by arbitrary components with the same formatting rule.

introduce UnitsService

---

src/modules/map/components/layerManager/LayerManager.js
test/modules/map/components/layerManager/LayerManager.test.js

update LayerManager to filter layers with 'hidden'-constraint evaluated
to `true`, to prevent rendering of related information. This behavior is needed
for instance for session-layers of tools.

update LayerManager for hidden layer

---

src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
src/modules/map/i18n/olMap.provider.js
src/utils/timer.js
test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
test/modules/map/i18n/olMap.provider.test.js

after successful creating measurement-data, the data should be converted/promoted from session-data to full-qualified georesource-data

measurement -  persist data

---

src/modules/BaElement.js
src/modules/menu/components/mainMenu/MainMenu.js
src/services/provider/geoResource.provider.js
test/modules/BaElement.test.js
test/modules/menu/components/mainMenu/MainMenu.test.js

Util to include other imported BaElements in a view without knowing their exact tag.
````
import { renderTagOf } from ...
import { BaseLayerSwitcher } from ...
//and in createView()
return html`
<div>
${renderTagOf(BaseLayerSwitcher)}		
</div>
`;
````
We can directly reference the tag of an imported BaElement and do not need to reference them by a fragile string.
No support for attributes (and not planned).

Add a util function for rendering BaElement tags

---

src/modules/BaElement.js
src/modules/baseLayer/components/switcher/BaseLayerSwitcher.js
src/modules/contextMenue/components/ContextMenue.js
src/modules/footer/components/Footer.js
src/modules/footer/components/baseLayerInfo/BaseLayerInfo.js
src/modules/footer/components/coordinateSelect/CoordinateSelect.js
src/modules/header/components/Header.js
src/modules/map/components/attributionInfo/AttributionInfo.js
src/modules/map/components/contextMenu/MapContextMenu.js
src/modules/map/components/geolocationButton/GeolocationButton.js
src/modules/map/components/infoButton/InfoButton.js
src/modules/map/components/layerManager/LayerManager.js
src/modules/map/components/olMap/OlMap.js
src/modules/menu/components/mainMenu/MainMenu.js
src/modules/menu/components/mediaQueryPanel/MediaQueryPanel.js
src/modules/menu/components/sidePanel/SidePanel.js
src/modules/menu/components/toolBar/ToolBar.js
src/modules/modal/components/Modal.js
src/modules/toolbox/components/measureToolContent/MeasureToolContent.js
src/modules/toolbox/components/toolContainer/ToolContainer.js
src/modules/uiTheme/components/provider/ThemeProvider.js
src/modules/uiTheme/components/toggle/ThemeToggle.js
test/modules/BaElement.test.js

Dear BA Devs, 
access to an element's state based on `this._state` is not allowed anymore ☝️
Use instead:
-  `createView(state)`
-  `this.getState()`

Rework state access in BaElement

---

src/modules/BaElement.js
src/modules/map/components/olMap/OlMap.js
test/modules/BaElement.test.js
test/modules/map/components/olMap/OlMap.test.js

BaElement:
- allow multiple fields name
- add the possibility for an  immediate callback call after registration
OlMap:
- use the changes to synchronize view and layers separately

Improve BaElement's observe method

---

src/modules/map/components/olMap/OlMap.js
src/modules/map/components/rotationButton/RotationButton.js
src/services/MapService.js
test/modules/map/components/olMap/OlMap.test.js
test/modules/map/components/rotationButton/RotationButton.test.js
test/service/MapService.test.js

- avoid flickering of the icon button when rotating the map
- move the definition of the rotation threshold value to MapService

Avoid flickering of the rotation icon button

---

src/modules/map/components/olMap/services/LayerService.js
test/modules/map/components/olMap/services/LayerService.test.js

fixes #351 
Background information: The vector source already has its own loader which uses  the `NetworkStateSyncHttpService`
for managing the `fetching` state. So, the "featureload" registration on the ol source has to be removed.

remove featureload event registration

---

karma.conf.js
test/modules/map/components/layerManager/LayerManager.test.js
test/modules/modal/components/Modal.test.js

fixes #387
it seems that the Playwright Webkit browser (Safari 14, Headless) does not update the invisible elements. Therefore, the tests are more detailed and only the visible elements are tested.

fix test expectations in LayerManager.test

---

src/index.html
src/modules/commons/components/icon/Icon.js
src/modules/commons/components/icon/icon.css
src/modules/map/components/contextMenu/MapContextMenu.js
src/modules/map/components/contextMenu/MapContextMenuContent.js
src/modules/map/components/contextMenu/assets/checked.svg
src/modules/map/i18n/contextMenu.provider.js
src/modules/map/store/ContextClickPlugin.js
src/modules/map/store/mapContextMenu.action.js
src/modules/map/store/mapContextMenu.reducer.js
test/e2e/page.spec.js
test/modules/commons/components/Icon.test.js
test/modules/map/components/contextMenu/MapContextMenu.test.js
test/modules/map/components/contextMenu/MapContextMenuContent.test.js
test/modules/map/i18n/contextMenu.provider.test.js
test/modules/map/store/ContextClickPlugin.test.js

Similar to our Modal window, the content of our ContextMenu should be submitted by the payload of the corresponding action.
Bonus: The copy-to-clipboard icons change their layout on success.

Rework ContextMenu 

---

test/modules/map/components/olMap/handler/featureInfo/OlFeatureInfoHandler.test.js

to prevent flaky tests in `OlFeatureInfoHandler.test.js` (see https://github.com/ldbv-by/bav4-nomigration/runs/4350856533)

increase delay time

---

src/modules/map/components/olMap/handler/draw/OlDrawHandler.js
test/modules/map/components/olMap/handler/draw/OlDrawHandler.test.js

fixes #560
update OlDrawHandler.onDeactivate() by moving reset-statements
for styles upwards, to prevent reinitializing of draw-interactions

Fix order of statements in  OlDrawHandler.onDeactivate

---

src/modules/toolbox/components/drawToolContent/DrawToolContent.js
test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js

In the DrawToolContent the user can change the style of the drawing.
Changes on Color- and Text-Style are made with Input-elements.
Switching to listen to input-events  leads to a more
responsive behavior of the DrawToolContent

update styling-behavior by using Input-Event

---

README.md
package.json

We can safely use es10 and es11 language features from now on
- https://caniuse.com/?search=es10
- https://caniuse.com/?search=es11

move from es9 to es11

---

test/modules/map/components/olMap/handler/featureInfo/OlFeatureInfoHandler.test.js

use `rendercomplete` instead of `postrender`
fixes #576

prevent flakiness in OlFeatureInfoHandler

---

src/modules/map/components/olMap/services/MeasurementStorageService.js
test/modules/map/components/olMap/services/MeasurementStorageService.test.js

Fixing the behavior of MeasurementStorageService, to write the received FileSaveResult to both, draw- and measurement-store.
@taulinger : the fix writes currently in both slices (draw and measure) the same fileSaveResult, should we cut the store at this point into a extra data-slice (i could'nt find a good name ...storage?data? whatsoever...) in the store?
Instead of:  
- store/measurement/fileSaveResult
- store/draw/fileSaveResult
seperated in only:
- store/[data-slice]

fix for drawing/measurement-store

---

src/modules/map/components/olMap/handler/draw/OlDrawHandler.js
src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
test/modules/map/components/olMap/handler/draw/OlDrawHandler.test.js
test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js

OlMeasurementHandler - move registration for store-changes
from ctor() to activate()
OlDrawHandler - move registration for store-changes within activate()
add tests for activate->reset->deactivate->activate-behavior
fixes #600

fix observer-registration

---

src/modules/map/components/olMap/handler/draw/OlDrawHandler.js

Fixing unnecessarily triggered calls of _save(), caused by changes of unfinished drawn features.
This happens after drawing a feature (without deselect) and closing the drawTool immediately

prevent unnecessarily triggered save  onDeactivate

---

package-lock.json
package.json
test/modules/map/components/olMap/handler/geolocation/styleUtils.test.js
test/modules/map/components/olMap/handler/highlight/styleUtils.test.js

Bumb openLayers to version 6.11.0 and update tests
Due to changes in `ol/render - getVectorContext(event)` some tests need a full instance of CanvasRenderingContext2D instead of a stub.

Bump ol from 6.9.0 to 6.11.0

---

src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js

fixes behavior in OlMeasurementHandler, where multiselection of arbitary features (draw- and measure-feature) does not resolve in a update of the statistic-values in the store

fix update measure stats in store on multiselect

---

src/modules/dndImport/components/DndImportPanel.js
test/modules/dndImport/components/DndImportPanel.test.js

update of the drag&drop-behavior in DndImportPanel, where a
unintended activation of the dropzone by dragged LayerItems is
prevented by checking for emptyness of the dataTransfer.types-Array.
Any other type than the known importTypes (File, text/plain) will
still result in a message being displayed.

fix unintended activation of Dropzone

---

src/modules/map/components/olMap/services/VectorLayerService.js
src/services/GeoResourceService.js
src/services/domain/geoResources.js
src/services/provider/geoResource.provider.js
test/modules/map/components/attributionInfo/AttributionInfo.test.js
test/plugins/LayersPlugin.test.js
test/service/ImportVectorDataService.test.js
test/service/domain/geoResources.test.js
test/service/provider/geoResource.provider.test.js

Improves and unifies handling of optional properties for GeoResources and provides a basis for adding further optional properties for all kinds of GeoResources.

georesources: assign optional properties by method

---

src/modules/baseLayer/components/switcher/BaseLayerSwitcher.js
test/modules/baseLayer/components/BaseLayerSwitcher.test.js

Allow multiple layers for the same GeoResource.
When a layer referencing a base GeoResource is not on index = 0, a second layer for that GeoResource can be added.
Fixes #705

alter BaseLayerSwitcher behavior

---

src/modules/toolbox/components/measureToolContent/MeasureToolContent.js
test/modules/toolbox/components/measureToolContent/MeasureToolContent.test.js

creating test ids on elements for:
- distance-value and -unit
- area-value and -unit
- action-buttons ('startNew','remove', 'finish')

MeasureToolContent: add test-ids for acceptance-tests

---

src/modules/map/components/olMap/handler/draw/OlDrawHandler.js
src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
src/modules/map/components/olMap/services/StyleService.js
src/modules/map/components/olMap/services/VectorLayerService.js
test/modules/map/components/olMap/handler/draw/OlDrawHandler.test.js
test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
test/modules/map/components/olMap/services/StyleService.test.js
test/modules/map/components/olMap/services/VectorLayerService.test.js

Features without style-information are provided with a default style. 
The current implementation sets a default style with a different color for each feature, regardless of whether the objects all belong to the same layer or not. 
With this enhancement we try to establish a reliable way to set a default style for unstyled features per layer, as it is a standard behavior in desktop gis.

Default-Style use layer-based color

---

src/assets/config.js
src/main.js
src/services/ProcessEnvConfigService.js
test/e2e/entryPoints.spec.js
test/service/ProcessEnvConfigService.test.js
webpack.config.js

Config parameters are set within the `.env` file and loaded from the `process.env` object by the ProcessEnvConfigService.
Additionally, config parameters can be also set now via a `window.config` object, appointed within a script provided from `/config.js`.

optionally load external config

---

src/modules/toolbox/components/measureToolContent/MeasureToolContent.js
test/modules/toolbox/components/measureToolContent/MeasureToolContent.test.js

update creation of action-buttons to circumvent the behavior, that a changed measure state, initiated by a button-click, does not reflect in losing focus for a new button on the same position. Switching from a Array of TemplateResult to a single TemplateResult.
fixes #835

fix button-focus on measurement state-changes

---

src/index.html
test/e2e/page.spec.js

Android notification bar should have the same color as our header depending on the current theme:

adjust theme-colors

---

src/modules/map/components/olMap/handler/featureInfo/OlFeatureInfoHandler.js
src/modules/map/components/olMap/handler/highlight/OlHighlightLayerHandler.js
src/plugins/ContextClickPlugin.js
src/plugins/HighlightPlugin.js
src/store/highlight/highlight.action.js
test/modules/map/components/olMap/handler/featureInfo/OlFeatureInfoHandler.test.js
test/modules/map/components/olMap/handler/highlight/OlHighlightLayerHandler.test.js
test/plugins/ContextClickPlugin.test.js
test/plugins/HighlightPlugin.test.js
test/store/highlight/highlight.action.test.js

Let's use the same symbol we use for a successful feature info indication

change feature highlight for long-press results

---

src/modules/map/components/olMap/handler/draw/OlDrawHandler.js
test/modules/map/components/olMap/handler/draw/OlDrawHandler.test.js

Corrects the updateStyle-behavior by merging correctly the new, changed style, with the current style-array.
This results in a replacement of the first entry in the style-array.
update test; reflecting the changed expectations setStyle should be called with [newStyle, oldStyle2]
fixes #881

fix updatestyle-behavior

---

src/modules/help/components/firststeps.css
src/utils/storeUtils.js
test/utils/storeUtils.test.js

make `equal` generally valid including  `{ a:0, b:1 } === { b:1, a:0 } `

improve deep comparision approach

---

src/modules/map/components/olMap/handler/measure/MeasurementOverlayStyle.js
test/modules/map/components/olMap/handler/measure/MeasurementOverlayStyle.test.js
test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
test/modules/map/components/olMap/services/OverlayService.test.js
test/modules/map/components/olMap/services/StyleService.test.js

update the process of creating measurement-overlays. The draggable-behavior of a MeasurementOverlay now depends whether there is a touch-environment detected and an active measurement-session or not.
fixes #922

update creation of  MeasurementOverlays

---

src/modules/map/components/olMap/handler/measure/MeasurementOverlayStyle.js
src/modules/map/components/olMap/olGeometryUtils.js
test/modules/map/components/olMap/handler/measure/MeasurementOverlayStyle.test.js
test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js

Under some circumstances the measurement-overlays overlapping each other...
With this enhancement, the calculation is updated to prevent the overlap.

Prevent overlapping MeasurementOverlays

---

src/modules/map/components/olMap/handler/measure/MeasurementOverlayStyle.js
test/modules/map/components/olMap/handler/measure/MeasurementOverlayStyle.test.js
test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js

add event-handling on 'pointerup 'for a dragged overlay-element to reactivate DragPan-interaction
fixes #922

reactivate DragPan after dragging overlay

---

src/modules/featureInfo/components/featureInfoPanel.css

add: auto width for th and td tags

---

src/services/provider/stringifyCoords.provider.js
test/service/provider/stringifyCoords.provider.test.js

Instead of simple reverse the order of assumed 2D coordinate-array only
switching the XY-part of the coordinate-array to left the righter
parts (Z,...) untouched.
fixes #994

fix createStringLatLong

---

src/modules/header/components/Header.js
src/plugins/MainMenuPlugin.js
test/modules/header/components/Header.test.js
test/plugins/MainMenuPlugin.test.js

When search.query state changes, our Search UI should reflect it

search query state changes should trigger SearchUI

---

src/modules/dndImport/components/DndImportPanel.js
test/modules/dndImport/components/DndImportPanel.test.js

Adding the option to drag&drop a wms url.
Due to the fact, that the user must select a specific layer, the georecource is not added to the map immediatly, but displayed as SearchResult. This is already implemented and now used by setQuery in search.action.

recognize wms-url in DndImportPanel and use setQuery

---

src/modules/layerManager/components/LayerItem.js
test/modules/layerManager/components/LayerItem.test.js
test/modules/layerManager/components/LayerManager.test.js

The zoomToExtent-Button in the LayerItem will be not visible, when the
georecource of a layer is not a VectorGeoResource.

update visibility of zoomToExtent-button

---

src/modules/commons/components/overflowMenu/OverflowMenu.js
src/modules/commons/components/overflowMenu/menuitem.css
src/modules/layerManager/components/LayerItem.js
test/modules/commons/components/OverflowMenu.test.js
test/modules/layerManager/components/LayerItem.test.js

Add a overflow-menu to remove buttons connected to less important (and volatile) actions from the LayerItem and to regain space for the more important and often used controls.

Add menu to LayerItem

---

src/modules/olMap/handler/draw/OlDrawHandler.js
src/modules/olMap/utils/olStyleUtils.js
test/modules/olMap/util/olStyleUtils.test.js

Add scale information of selected features to the changed styleOption in store, to display the correct scale-value in the DrawToolContent
fixes #1104

fix StyleOptions of selected feature

---

src/modules/olMap/handler/draw/OlDrawHandler.js
src/modules/olMap/utils/olStyleUtils.js
test/modules/olMap/util/olStyleUtils.test.js

Add scale information of selected features to the changed styleOption in
store, to display the correct scale-value in the DrawToolContent

fix StyleOptions of selected feature (cherry-pick)

---

src/services/provider/wmsCapabilities.provider.js
test/service/provider/wmsCapabilities.provider.test.js

We should not just take the first media type for GetMap requests from the GetCapabilities document, 
but determine the best suitable one.

determine preferred getMap media type

---

src/modules/toolbox/components/toolBar/toolBar.css

fix: Collapsed toolbar still visible

fix collapsed toolbar

---

src/injection/config.js
src/plugins/ExportMfpPlugin.js
src/services/MfpService.js
src/services/provider/mfp.provider.js
test/plugins/ExportMfpPlugin.test.js
test/service/MfpService.test.js
test/service/mfp.provider.test.js

For the present just  `MfpService#getCapabilities()` has been implemented, the other methods will be done in a second PR and are still mocked.

PdfExport: connect client with backend (I)

---

src/plugins/ExportMfpPlugin.js
test/plugins/ExportMfpPlugin.test.js

PDF seems to be  loaded smother in most browsers when fetched via `window.location`

optimize PDF loading

---

src/modules/olMap/handler/mfp/OlMfpHandler.js
src/modules/olMap/services/Mfp3Encoder.js
test/modules/olMap/formats/Mfp3Encoder.test.js

Fixes a misbehavior where the label content of the thumbnail-style was not updated, after the mfp settings are changed.
The thumbnail-style is used to display the currently selected mfp-settings and extent as preview for the export.

fix content of thumbnailLabel

---

src/modules/olMap/services/Mfp3Encoder.js
test/modules/olMap/formats/Mfp3Encoder.test.js

adding transparent:true to encoded MFP  specs of a WMS layer, by adding the customParams property

Export2Pdf: add a default parameter to encoded WMS

---

src/modules/toolbox/components/measureToolContent/MeasureToolContent.js
src/services/provider/units.provider.js
test/modules/toolbox/components/measureToolContent/MeasureToolContent.test.js
test/service/UnitsService.test.js
test/service/provider/units.provider.test.js

remove usage of `&sup2;` to prevent unnecessary encode- and decode-calls

remove usage of HTML Entities

---

src/modules/olMap/services/Mfp3Encoder.js
test/modules/olMap/formats/Mfp3Encoder.test.js

fix encoding for features with a default style, caused by features without any styleinformation from a kml-source

Export2Pfd: fix default style handling 

---

src/modules/MvuElement.js
src/utils/markup.js
test/modules/MvuElement.test.js
test/test-utils.js
test/utils/markup.test.js

Add possibility to enable logging of  a components life-cycle in order to help tracing its changes of state
according to the underlying MVU pattern.
A possible result would be:
```
LOG: '📦 MvuElementImpl#constructor: {"foo":"foo","index":null}'
LOG: '🎺 MvuElementImpl#signal: "update_index", 21'
LOG: '📌 MvuElementImpl#onModelChanged: {"foo":"foo","index":21}'
LOG: '📌 MvuElementImpl#onInitialize'
LOG: '📌 MvuElementImpl#onBeforeRender'
LOG: '🧪 MvuElementImpl#render: {"foo":"foo","index":21}'
LOG: '📌 MvuElementImpl#onAfterRender'
LOG: '📌 MvuElementImpl#onDisconnect'
```
How to enable the life-cycle logging?
- during runtime / in production:  by appending the `data-log-lifecycle` attribute, e.g. `<my-element data-log-lifecycle></my-element>`
- in tests:  use `TestUtils#renderAndLogLifecycle` …

add life-cycle logging for MvuElements

---

.gitignore
karma.conf.single.js
package-lock.json
package.json

Use a reporter for mocha-style logging (https://github.com/litixsoft/karma-mocha-reporter) and redirect all console output to the dedicated file `console.log`.  Affects only the single-test mode.
Background:
By separating the test report from the console output,  we get a better overview of the current test setup on one hand, on the other hand, we have a clean and duplicate-free view of all console log statements.
Examples:
- Test report
- console.log:

adjust single test report

---

src/modules/olMap/components/OlMap.js
test/modules/olMap/components/OlMap.test.js
test/test-utils.js

Prevent double calls of map actions (movestart, moving, moveend).

OlMap: prevent double calls of map actions

---

src/modules/map/components/attributionInfo/AttributionInfo.js
test/modules/map/components/attributionInfo/AttributionInfo.test.js
test/test-utils.js

The order of attributions should basically reflect the order of map layers now.
Resolves #1345

revert order of attributions

---

src/domain/geoResources.js
src/modules/map/components/attributionInfo/AttributionInfo.js
src/services/provider/geoResource.provider.js
test/modules/map/components/attributionInfo/AttributionInfo.test.js
test/service/provider/geoResource.provider.test.js

An `attribution` object can contain also an array of  `copyright` objects now.

Attribution data: adjust to backend changes

---

src/services/GeoResourceService.js
src/services/ImportVectorDataService.js
src/services/ImportWmsService.js
src/services/provider/geoResource.provider.js
src/services/provider/wmsCapabilities.provider.js
test/service/GeoResourceService.test.js
test/service/ImportWmsService.test.js
test/service/provider/geoResource.provider.test.js
test/service/provider/wmsCapabilities.provider.test.js

An URL-based ID for GeoResource must match the following pattern:
KML,GPX,GEOJSON,EWKT:
`{url}`||`[{label}]`
WMS:
`{url}`||`{layer}`||`[{label}]`
e.g. `?l=https://foo.bar||wmsLayer0,MyWms,https://foo.bar/kml`

load URL-based GeoResources from QueryParameters

---

src/plugins/HistoryStatePlugin.js
test/plugins/HistoryStatePlugin.test.js

Avoid throwing an exception due to too many calls to History API within a short timeframe.

prevent unnecessary calls of History API

---

src/domain/geoResources.js
src/modules/geoResourceInfo/services/GeoResourceInfoService.js
src/modules/geoResourceInfo/services/provider/geoResourceInfoResult.provider.js
src/services/ImportWmsService.js
src/services/provider/featureInfo.provider.js
test/domain/geoResources.test.js
test/modules/geoResourceInfo/services/GeoResourceInfoService.test.js
test/modules/geoResourceInfo/services/provider/geoResourceInfoResult.provider.test.js
test/service/ImportWmsService.test.js
test/service/provider/featureInfo.provider.test.js

rework GeoResourceInfo handling for imported GeoResources

---

src/modules/stackables/components/BottomSheet.js
test/modules/stackables/components/BottomSheet.test.js

fixes #1452
Move the subscription to store changes into the constructor phase and complete the lifecycle with the unsubscribe call in the disconnect-callback.

BottomSheet: unsubscribe the observer 

---

src/domain/pathParameters.js
src/services/ShareService.js
test/domain/pathParameters.test.js
test/service/ShareService.test.js

Encode current state for embed page:
`shareService.encodeState({}, [PathParameters.EMBED]);`

ShareService: handle optional path parameter

---

src/injection/config.js
src/plugins/IframeStatePlugin.js
src/services/StoreService.js
src/utils/markup.js
test/injection/config.test.js
test/plugins/IframeStatePlugin.test.js
test/service/StoreService.test.js
test/utils/markup.test.js

By adding the  `data-iframe-encoded-state` attribute to an iframe element, it will expose the current encoded state of an embedded BA app:
```
<iframe data-iframe-encoded-state src="../embed.html"></iframe>
```
will be updated on state changes, e.g.
```
<iframe data-iframe-encoded-state="http://localhost:8080/embed.html?c=677751,5422939&amp;z=7&amp;l=atkis&amp;t=ba" src="../embed.html"></iframe>
```

add possibiltiy to expose the current encoded state of an embedded BA app 

---

src/modules/olMap/formats/kml.js
src/modules/olMap/handler/draw/OlDrawHandler.js
src/modules/olMap/handler/measure/OlMeasurementHandler.js

fixes #1503
the shortcut method 'readFeature' is not sufficient testable. Replacing the usage with the usage of ol format object.

KML: remove shortcut method

---

src/modules/iframe/components/iframeGenerator/IframeGenerator.js
src/plugins/IframeStatePlugin.js
src/services/ShareService.js
test/modules/iframe/components/IframeGenerator.test.js
test/plugins/IframeStatePlugin.test.js
test/service/ShareService.test.js

`encodeState()` will ignore an existing pathname from the current location now. If needed it always has to be requested as a path parameter,
e.g.: `shareService.encodeState({}, [PathParameters.EMBED]);`

ShareService: ignore existing pathname

---

src/injection/config.js
src/plugins/HistoryStatePlugin.js
src/plugins/IframeStatePlugin.js
src/plugins/ObserveStateForEncodingPlugin.js
src/services/ShareService.js
src/services/StoreService.js
src/store/stateForEncoding/stateForEncoding.action.js
src/store/stateForEncoding/stateForEncoding.reducer.js
test/injection/config.test.js
test/plugins/HistoryStatePlugin.test.js
test/plugins/IframeStatePlugin.test.js
test/plugins/ObserveStateForEncodingPlugin.test.js
test/service/StoreService.test.js
test/store/stateForEncoding/stateForEncoding.reducer.test.js

Adds a central observer on encoding-relevant parts of our state.
Other modules interested in encoding-relevant state changes just have to observe `stateForEncoding.changed` now.

rework state encoding

---

src/injection/config.js
src/modules/olMap/handler/draw/OlDrawHandler.js
src/modules/olMap/handler/measure/OlMeasurementHandler.js
src/modules/olMap/services/InteractionStorageService.js
src/plugins/IframeGeometryIdPlugin.js
src/plugins/IframeStatePlugin.js
src/services/StoreService.js
src/store/draw/draw.action.js
src/store/draw/draw.reducer.js
src/store/measurement/measurement.action.js
src/store/measurement/measurement.reducer.js
src/utils/markup.js
test/injection/config.test.js
test/modules/olMap/handler/draw/OlDrawHandler.test.js
test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
test/modules/olMap/services/InteractionStorageService.test.js
test/plugins/IframeGeometryIdPlugin.test.js
test/plugins/IframeStatePlugin.test.js
test/service/StoreService.test.js
test/store/draw/draw.reducer.test.js
test/store/measurement/measurement.reducer.test.js
test/utils/markup.test.js

Checks if a surrounding iframe exists and contains the IFRAME_GEOMETRY_REFERENCE_ID data attribute.
If so, it updates the attribute's value on changes in the fileSaveResult property of the draw slice-of-state.

IframeGeometryIdPlugin

---

src/i18n/global.provider.js
src/modules/layerManager/components/LayerItem.js
src/modules/olMap/handler/draw/OlDrawHandler.js
src/modules/olMap/handler/measure/OlMeasurementHandler.js
src/services/provider/fileStorage.provider.js
test/i18n/global.provider.test.js
test/modules/layerManager/components/LayerItem.test.js
test/modules/olMap/handler/draw/OlDrawHandler.test.js
test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
test/service/provider/fileStorage.provider.test.js

When more than one "drawing" layer exists and the measurement or drawing tool is activated the topmost "drawing" layer is taken as the source.
Also fixes #1628 and fixes #1627

allow cloning of stored layer

---

src/modules/utils/components/showCase/ShowCase.js

After it has been successfully placed in the menu, it is no longer needed in the showcase.

MapFeedback: remove Feedback components from ShowCase

---

src/modules/olMap/handler/draw/OlDrawHandler.js
src/modules/olMap/handler/measure/OlMeasurementHandler.js
src/plugins/IframeGeometryIdPlugin.js
test/plugins/IframeGeometryIdPlugin.test.js

update the behavior of the method '_updateAttribute' to empty string instead of null, du to the behavior of the setAttribute-method of HtmlElements, which
causes an implicit stringify of null-values.
An empty string ('') can be easier evaluated then 'null'.

IframeGeometryIdPlugin: fix updateAttribute to emptyString

---

src/services/FeedbackService.js
src/services/GeoResourceService.js
src/services/provider/feedback.provider.js
src/services/provider/geoResource.provider.js
test/service/provider/geoResource.provider.test.js

All URL-based VectorGeoResource are loaded by a GeoResourceFuture now.
Implicitly fixes #1685

rework loading of URL-based VectorGeoResource

---

src/modules/olMap/services/StyleService.js
test/modules/olMap/services/StyleService.test.js

Updating StyleService for added features without existing style but id and attribute leading to style-information about marker- or text-styles.
This use case can occur when a feature is imported from a geojson resource.

StyleService: update styling-behavior for features without style

---

src/i18n/global.provider.js
src/modules/olMap/handler/featureInfo/OlFeatureInfoHandler.js
src/modules/olMap/handler/featureInfo/featureInfoItem.provider.js
src/modules/olMap/handler/highlight/OlHighlightLayerHandler.js
src/plugins/HighlightPlugin.js
test/i18n/global.provider.test.js
test/modules/olMap/handler/featureInfo/OlFeatureInfoHandler.test.js
test/modules/olMap/handler/featureInfo/featureInfoItem.provider.test.js
test/modules/olMap/handler/highlight/OlHighlightLayerHandler.test.js
test/plugins/HighlightPlugin.test.js

Features of hidden layers are selectable if they contain a `name` property.

make highlight features selectable

---

package-lock.json
package.json
test/modules/olMap/services/LayerService.test.js

`maplibre-gl` comes as a peer dependency from `ol-maplibre-layer`. In order to use its latest version we add it as a direct dependency.

add maplibre-gl as direct dependency

---

src/modules/stackables/components/bottomSheet/bottomSheet.css

due to the inheritance of some CSS properties(e.g. color) into the child component, the color property is not required or may even lead to unwanted display problems
fixes #1826

bottomSheet.css: remove text color

---

test/modules/olMap/handler/draw/OlDrawHandler.test.js

fix tests to ensure a valid state of the store, by waiting for completion of setup
fixes #1832

OlDrawHandler: fix tests

---

src/services/IconService.js
test/service/IconService.test.js

bug workflow:
1.  open draw dialog
2.  select "symbol"
3.  open "style" area 
4.  choose another color
result:
-     no drawing of symbol is possible any more
-     there is no icon selected inside "style" area
This pull requests changes the inital value of the marker to "marker.png" as the matcher function of the IconResult class only matches if the URL ends with "/${id}.png"

 drawing of symbol not possible after style color is changed

---

README.md
checkOrApplyDoc.js
src/chunks/elevation-profile.js
src/modules/commons/components/lazy/LazyLoadWrapper.js
src/modules/commons/components/lazy/index.js
src/modules/commons/index.js
src/modules/elevationProfile/index.js
src/plugins/ElevationProfilePlugin.js
test/chunkUtil/mockChunk.js
test/e2e/entryPointsAndChunks.spec.js
test/modules/commons/components/LazyLoadWrapper.test.js
test/modules/feedback/components/toggleFeedback/ToggleFeedbackPanel.test.js
test/plugins/ElevationProfilePlugin.test.js
webpack.config.js
webpack.test.config.js

In this PR the ElevationProfile component and its dependencies (incl. Chart.js) are loaded dynamically on demand by using webpack's dynamic import feature.
The initial build size decreases by almost 10% from 2.97 MiB to  2.77 MiB.
This feature will get much more interesting when we are trying to integrate something like Cesium.js.

add lazy loading/dynamic import of component

---

src/modules/olMap/handler/draw/OlDrawHandler.js
src/modules/olMap/utils/olInteractionUtils.js
test/modules/olMap/handler/draw/OlDrawHandler.test.js
test/modules/olMap/handler/measure/OlMeasurementHandler.test.js

OlDrawHandler: always clear drawing listeners

---

src/modules/olMap/utils/olStyleUtils.js
test/modules/olMap/util/olStyleUtils.test.js

Currently when creating a symbol with text, the text is shown inside the symbol:
Show the text under the symbol:

Drawing: Show text under symbol instead of inside symbol

---

src/modules/menu/components/mainMenu/MainMenu.js
src/modules/menu/components/mainMenu/content/AbstractMvuContentPanel.js
src/modules/topics/components/menu/TopicsContentPanel.js
test/modules/featureInfo/components/FeatureInfoPanel.test.js
test/modules/menu/components/mainMenu/MainMenu.test.js
test/modules/menu/components/mainMenu/content/AbstractMvuContentPanel.test.js
test/modules/menu/components/mainMenu/content/RoutingPanel.test.js
test/modules/topics/components/menu/TopicsContentPanel.test.js

Allows lazy loading of the content now:
```
export class MyPanel extends AbstractMvuContentPanel {
createView(model) {
const { active } = model;
return active ?  ...
```

extend MvuContentPanel

---

src/domain/queryParameters.js
src/plugins/LayersPlugin.js
test/domain/queryParameters.test.js
test/plugins/LayersPlugin.test.js

This PR restores a currently missing functionality. In v3 we have the query parameter `kmlZoomToExtent` to realize a fit of the map on the extent of one layer.
Now in v4, the parameter `zte` references the index of the layer which should be used for fitting.
Example URL (for review):
http://localhost:8080/?c=-13.45104,46.96160&z=5&l=atkis,https%3A%2F%2Fgeodaten.bayern.de%2Fodd%2Fm%2F3%2Fdaten%2Ffreizeit%2Fkml%2Frodelbahnen.kml&t=ba&zte=1

add QueryParameter for zooming on the extent of a layer

---

src/modules/olMap/components/OlMap.js
src/modules/olMap/handler/selectableFeature/OlSelectableFeatureHandler.js
src/modules/olMap/injection/index.js
src/utils/storeUtils.js
test/injection/config.test.js
test/modules/olMap/components/OlMap.test.js
test/modules/olMap/handler/selectableFeature/OlSelectableFeatureHandler.test.js

Changes the cursor when a vector feature or a pixel of a WMS or tile image is selectable.
The default cursor will change to a pointer (👆) in the following cases:

indicate when a feature is selectable

---

src/modules/olMap/formats/kml.js
test/modules/olMap/formats/kml.test.js

The replacement of an SVG resource is updated to a expected NULL as a result of the IconService request
IconService.getIconResult(idOrUrlOrBase64). The behavior changes to: return the old image to enable the creation of a (local) kml-layer, which cannot be exported.

KML: update icon-replace behavior

---

src/plugins/RoutingPlugin.js
test/plugins/RoutingPlugin.test.js

when the routing tool is activated, it also
- closes the context menu
- removes existing highlight features

adjust routing plugin

---

src/modules/olMap/services/LayerService.js
src/modules/olMap/utils/baaImageLoadFunction.provider.js
src/services/HttpService.js
test/service/FeedbackService.test.js
test/service/HttpService.test.js
test/service/provider/mfp.provider.test.js

Extend the `HttpService` for registering a response interceptor.
A request interceptor may be supported in the future.

configurable response interceptor

---

.github/workflows/node.js.yml
src/domain/geoResources.js
src/i18n/global.provider.js
src/injection/config.js
src/modules/olMap/components/OlMap.js
src/modules/olMap/services/LayerService.js
src/modules/olMap/utils/baaImageLoadFunction.provider.js
src/modules/olMap/utils/olLoadFunction.provider.js
src/plugins/GlobalErrorPlugin.js
src/services/AuthService.js
src/services/GeoResourceService.js
src/services/HttpService.js
src/services/ImportVectorDataService.js
src/services/ProcessEnvConfigService.js
src/services/provider/auth.provider.js
src/services/provider/fileStorage.provider.js
src/services/provider/geoResource.provider.js
test/e2e/page.spec.js
test/i18n/global.provider.test.js
test/modules/olMap/components/OlMap.test.js
test/modules/olMap/services/LayerService.test.js
test/modules/olMap/util/olLoadFunction.provider.test.js
test/plugins/GlobalErrorPlugin.test.js
test/service/GeoResourceService.test.js
test/service/HttpService.test.js
test/service/ImportVectorDataService.test.js
test/service/ProcessEnvConfigService.test.js
test/service/provider/auth.provider.test.js
test/service/provider/fileStorage.provider.test.js
test/service/provider/geoResource.provider.test.js

finetune authentication

---

README.md
src/modules/chips/components/assistChips/ElevationProfileChip.js
src/modules/elevationProfile/components/panel/ElevationProfile.js
src/modules/olMap/handler/elevationProfile/OlElevationProfileHandler.js
src/modules/olMap/handler/routing/OlRoutingHandler.js
src/plugins/ElevationProfilePlugin.js
src/services/ElevationService.js
src/store/elevationProfile/elevationProfile.action.js
src/store/elevationProfile/elevationProfile.reducer.js
test/modules/chips/components/ElevationProfileChip.test.js
test/modules/elevationProfile/components/panel/ElevationProfile.test.js
test/modules/olMap/handler/elevationProfile/OlElevationProfileHandler.test.js
test/modules/olMap/handler/routing/OlRoutingHandler.test.js
test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js
test/modules/toolbox/components/measureToolContent/MeasureToolContent.test.js
test/plugins/ElevationProfilePlugin.test.js
test/service/ElevationService.test.js
test/store/evelationProfile/elevationProfile.reducer.test.js

We avoid pushing huge arrays of coordinates to the store. Detecting changes can be expensive in that case. Instead, we reference them by an identifier and push this identifier to the store.
Fixes #2270

ElevationProfile: improve performance

---

src/domain/geoResources.js
src/modules/olMap/injection/index.js
src/modules/olMap/services/LayerService.js
src/modules/olMap/services/VectorLayerService.js
src/services/provider/geoResource.provider.js
test/domain/geoResources.test.js
test/injection/config.test.js
test/modules/olMap/services/LayerService.test.js
test/modules/olMap/services/VectorLayerService.test.js
test/service/provider/geoResource.provider.test.js

Add support for `RtVectorGeoresources`

add RtVectorGeoResource

---

src/plugins/AuthPlugin.js
src/services/AuthService.js
src/store/auth/auth.action.js
src/store/auth/auth.reducer.js
test/plugins/AuthPlugin.test.js
test/service/AuthService.test.js
test/store/auth/auth.reducer.test.js

Session invalidation due to session timeout should keep the active GeoResources, so the user can continue without re-selecting them

remove non-allowed GeoResources on sign-out only when initiated by the user

---

test/modules/olMap/util/olStyleUtils.test.js

remove flaky tests and replace with a test which tests the usage of a raster image source for the IconStyle

OlStyleUtils: remove tests with ol image load

---

src/modules/olMap/components/OlMap.js
test/modules/olMap/components/OlMap.test.js

Almost all GeoResources(except for the VtGeoResources) are loaded via the NetworkStateSyncHttpService now so there's no need for the ol.Map to update the network s-o-s itsself.
Fixes #2346

OlMap: remove obsolete network s-o-s update

---

src/modules/olMap/utils/olGeometryUtils.js
test/modules/olMap/util/olGeometryUtils.test.js

fixes #2368
Updates the behavior of multiLineStringToLineString to return null, when the given geometry did not match the geometry validation.
Valid geometry is:
- GeometryType -> MultiLineString
- all parts must be connected by its start and end nodes

olGeometryUtils: update behavior of multiLineStringToLineString

---

src/modules/elevationProfile/components/panel/ElevationProfile.js
test/modules/elevationProfile/components/panel/ElevationProfile.test.js

Fix the calculation of gradiant colorstops to maintain correct x-coordinate relative to the elements distance from profile start.

ElevationProfile: fix gradient calculation 

---

src/plugins/RoutingPlugin.js
src/plugins/ToolsPlugin.js
test/plugins/RoutingPlugin.test.js
test/plugins/ToolsPlugin.test.js

Please compare
- Active _Routing_ tool:  http://localhost:8080/?c=677751,5422939&z=8&r=0&l=atkis&t=ba&rtwp=1198066.0865566935,6267614.751015566,1311804.3846450357,6468797.00946215&rtc=bvv-hike&tid=routing
- Route is shown but no tool is  active; http://localhost:8080/?c=677751,5422939&z=8&r=0&l=atkis&t=ba&rtwp=1198066.0865566935,6267614.751015566,1311804.3846450357,6468797.00946215&rtc=bvv-hike&tid=
- Active _Export_ tool: http://localhost:8080/?c=677751,5422939&z=8&r=0&l=atkis&t=ba&rtwp=1198066.0865566935,6267614.751015566,1311804.3846450357,6468797.00946215&rtc=bvv-hike&tid=export

optimize routing-related query parameter handling

---

src/modules/olMap/handler/routing/OlRoutingHandler.js
src/plugins/RoutingPlugin.js
src/plugins/SharePlugin.js
test/modules/olMap/handler/routing/OlRoutingHandler.test.js
test/plugins/RoutingPlugin.test.js
test/plugins/SharePlugin.test.js

This PR avoids the following wrong notification:

SharePlugin: ignore hidden routing -related GeoResource (Ticket#45104510)

---

src/modules/olMap/handler/featureInfo/featureInfoItem.provider.js

Remove the process step of simplifying coordinates for the elevation profile, due to the fact that the profile provider does this implicit now. Any simplification beforehand is unnecessary.

FeatureInfoItem: remove simplify of elevation profile coordinates [Ticket#45104576]

---

src/modules/featureInfo/components/featureInfoIframePanel/featureInfoIframePanel.css
src/modules/featureInfo/components/featureInfoPanel/featureInfoPanel.css

style just works for links starts with "https://geodaten.bayern.de/odd/"
Test width:
?c=675914,5398336&z=11&r=0&l=atkis,https%3A%2F%2Fgeodaten.bayern.de%2Fodd%2Fa%2Flod2%2Fcitygml%2Fmeta%2Fkml%2Fgemeinde.kml&t=ba&tid=

Add style just for open data links

---

src/plugins/GlobalErrorPlugin.js
test/plugins/GlobalErrorPlugin.test.js

When a Georesource is unloadable, all referenced layers should be removed to keep the UI in sync

GlobalErrorPlugin: remove all associated layers from the layers s-o-s

---

src/modules/olMap/handler/draw/OlDrawHandler.js
src/modules/olMap/handler/measure/OlMeasurementHandler.js
src/modules/olMap/services/StyleService.js
test/modules/olMap/handler/draw/OlDrawHandler.test.js
test/modules/olMap/handler/measure/OlMeasurementHandler.test.js

update OlMeasurementHandler and OlDrawHandler, to prevent multiple unnecessary calls of _save/store
fixes #2477

v4.2: adding mapListener after old features are read

---

src/modules/olMap/handler/draw/OlDrawHandler.js
src/modules/olMap/handler/measure/OlMeasurementHandler.js
src/modules/olMap/services/StyleService.js
test/modules/olMap/handler/draw/OlDrawHandler.test.js
test/modules/olMap/handler/measure/OlMeasurementHandler.test.js

* adding mapListener after old features are read
* update OlMEasurementHandler and OlDrawHandler, to prevent multiple unnecessary calls of _save/store
* Ensure that transferred features are saved

adding mapListener after old features are read

---

src/plugins/EncodeStatePlugin.js
test/plugins/EncodeStatePlugin.test.js

... to avoid too many calls to the history API in a short period of time

EncodeStatePlugin: call replaceState() in a debounced manner

---

src/modules/chips/components/assistChips/ShareChip.js
src/plugins/HighlightPlugin.js
src/services/ShareService.js
test/modules/chips/components/ShareChip.test.js
test/plugins/HighlightPlugin.test.js
test/service/ShareService.test.js

This PR extends the CROSSHAIR query param by its coordinate to preserve the crosshair when shared after the map was relocated
```
http://localhost:8080/?crh=true,1340544.8149054,6318369.4588622
```
The coordinate is always in 3857.

always preseve the crosshair marker when sharing the map

---

src/modules/chips/components/assistChips/ShareDataChip.js
src/modules/public/components/PublicComponent.js
src/modules/toolbox/components/drawToolContent/DrawToolContent.js
src/modules/toolbox/components/measureToolContent/MeasureToolContent.js
src/plugins/IframeGeometryIdPlugin.js
src/store/fileStorage/fileStorage.action.js
src/store/fileStorage/fileStorage.reducer.js
test/modules/chips/components/ShareDataChip.test.js
test/modules/public/components/PublicComponent.test.js
test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js
test/modules/toolbox/components/measureToolContent/MeasureToolContent.test.js
test/plugins/IframeGeometryIdPlugin.test.js
test/store/fileStorage/fileStorage.reducer.test.js

adjust all classes which consume the `fileResult` property of the `draw` or `mesurement` s-o-s:

rework file storage: adjust file result consumer

---

src/plugins/MainMenuPlugin.js
test/plugins/MainMenuPlugin.test.js

Avoid opening the FeatureInfo tab when it is closed and no feature info was found

do not open the FeatureInfo tab when no result is available

---

src/modules/routing/components/waypoints/waypointItem.css

fix: icon size 45107039

---

src/plugins/ContextClickPlugin.js
src/plugins/ElevationProfilePlugin.js
src/plugins/RoutingPlugin.js
src/store/bottomSheet/bottomSheet.reducer.js
test/modules/commons/components/OverflowMenu.test.js
test/modules/olMap/handler/routing/OlRoutingHandler.test.js
test/modules/routing/components/ProposalContextContent.test.js
test/modules/stackables/components/BottomSheet.test.js
test/plugins/ContextClickPlugin.test.js
test/plugins/ElevationProfilePlugin.test.js
test/plugins/RoutingPlugin.test.js
test/plugins/TimeTravelPlugin.test.js
test/store/bottomSheet/bottomSheet.reducer.test.js

It's not easy in tests to detect when a certain bottom sheet is displayed and when not.
Therefore the following changes are made:
1. The `active` property is an array now and reflects all active bottom sheets. An empty array means no bottom sheet is active. This is the most important change
2.  A `BottomSheetContent` item will be removed from the `data` property when `closeBottomSheet` is called

rework the bottomSheet slice-of-state

---

src/modules/olMap/handler/mfp/OlMfpHandler.js
src/modules/olMap/handler/mfp/styleUtils.js

* fix mpf-layer render behavior
- add getRenderPixel() function to fix the calculation of the mfp mask
- rearrange the render methods

4.2 OlMfpHandler: update mfp-layer render behavior (#2598)

---

src/modules/olMap/handler/OlSketchHandler.js
src/modules/olMap/handler/measure/OlMeasurementHandler.js
test/modules/olMap/handler/measure/OlMeasurementHandler.test.js

remove the creating of geodesic geometry on OlSketchHandler.activate()
fixes #2647

OlSketchHandler: clean activate behavior  

---

src/modules/olMap/services/LayerService.js
test/modules/olMap/services/LayerService.test.js

Reduce the amount of HTTP requests by setting the TielLayer `preload` parameter to 0

set preload param to 0 for ol.TileLayer

---

src/modules/elevationProfile/components/panel/ElevationProfile.js

do not display the given max value, although the chart must be streched to this value

ElevationProfile:fix chartjs configuration for x axe

---

src/modules/olMap/services/Mfp3Encoder.js
test/modules/olMap/formats/Mfp3Encoder.test.js

reset QueryParameter 'TOOL_ID' to get a url without active ExportTool

Mfp3Encoder:  fix shortenedUrl for qrCode

---

src/modules/olMap/tooltip/HelpTooltip.js
test/modules/olMap/tooltip/HelpTooltip.test.js

for better readability of distance overlay
**Before**
**Optimized**

HelpTooltip: change positioning from center-left to top-left 

---

src/modules/olMap/components/OlMap.js
test/modules/olMap/components/OlMap.test.js

This reverts commit 90e0d348be814b49786acba2dd9554446e49b6bc which causes problems with the default  `DragZoom` interaction

Revert "pan map on pressing mouse wheel" (v4.3)

---

src/modules/olMap/components/OlMap.js
test/modules/olMap/components/OlMap.test.js

This reverts commit 90e0d348be814b49786acba2dd9554446e49b6bc which causes problems with the default  `DragZoom` interaction

Revert "pan map on pressing mouse wheel"

---

src/modules/toolbox/components/drawToolContent/DrawToolContent.js
test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js

add behavior to expand feature property form after first change to 'modify' (#2811)

DrawToolContent: expand property form after 'modify'

---

src/modules/olMap/formats/kml.js
test/modules/olMap/formats/kml.test.js

update cleaning rules for kml format to prevent `null` values in name and description tag

kml: prevent 'null' for description-tag (4.3)

---

src/modules/olMap/formats/kml.js
test/modules/olMap/formats/kml.test.js

update cleaning rules for kml format to prevent null values in name and description tag (#2822)

kml: prevent 'null' for description-tag

---

src/modules/olMap/handler/draw/OlDrawHandler.js
src/modules/olMap/handler/measure/OlMeasurementHandler.js
src/plugins/FileStoragePlugin.js
src/store/fileStorage/fileStorage.action.js
src/store/fileStorage/fileStorage.reducer.js
test/modules/olMap/handler/draw/OlDrawHandler.test.js
test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
test/plugins/FileStoragePlugin.test.js
test/store/fileStorage/fileStorage.reducer.test.js

* remove early save after reading rocksi features again
* change and rename action `setAdminId` to `setAdminAndFileId`
* set both the admin and the file ID if the admin id is available

FileStoragePlugin: also set  the fileID

---

src/modules/olMap/handler/measure/OlMeasurementHandler.js
test/modules/olMap/handler/measure/OlMeasurementHandler.test.js

When measuring starts and old features are read in, which are only drawings, the handler activates the draw-interaction. If at least one measurement feature exists in the old features, the handler activates the modify-interaction.

OlMeasurementHandler: optimize behavior after measurement is activated

---

src/modules/chips/components/assistChips/ShareChip.js
src/modules/share/components/dialog/ShareDialogContent.js
test/modules/chips/components/ShareChip.test.js
test/modules/share/components/shareDialogContent/ShareDialogContent.test.js
test/modules/toolbox/components/shareToolContent/ShareToolContent.test.js

* cleanup
* handle AbortError of ShareApi

avoid unnecessary warning messages when sharing is canceled (v4.3)

---

src/modules/olMap/services/VectorLayerService.js
test/modules/olMap/services/VectorLayerService.test.js

VectorLayerService: avoid displaying only one feature if ids are an empty string (v4.3)

---

src/modules/olMap/services/VectorLayerService.js
test/modules/olMap/services/VectorLayerService.test.js

VectorLayerService: avoid displaying only one feature if ids are an empty string

---

src/modules/elevationProfile/components/panel/ElevationProfile.js
src/modules/elevationProfile/components/panel/elevationProfile.css
src/modules/info/components/geometryInfo/GeometryInfo.js
src/modules/routing/components/routeDetails/RouteChart.js
src/modules/routing/components/routeInfo/RouteInfo.js
src/modules/toolbox/components/measureToolContent/MeasureToolContent.js
test/modules/elevationProfile/components/panel/ElevationProfile.test.js
test/modules/info/components/GeometryInfo.test.js
test/modules/routing/components/RouteChart.test.js
test/modules/routing/components/RouteInfo.test.js
test/modules/toolbox/components/measureToolContent/MeasureToolContent.test.js

Quantities are displayed in two ways:
1. `Quantity` (`unitOfMeasurement`): `numericValue` --> _'Distance (km): 42.1'_
2. `numericValue` `unitOfMeasurement` --> _'42.1 km'_
components to refactor:

Refactor formatting of quantities

---

src/plugins/LayersPlugin.js
test/plugins/LayersPlugin.test.js

Its VectorTile pendant is only used if we have a retina display
This reverts commit 099d0998bd198f2b1f7996862a075a84eff7bfc7.

Use raster layer as default bg layer again

---

src/modules/olMap/handler/draw/OlDrawHandler.js
src/modules/olMap/handler/measure/OlMeasurementHandler.js
src/modules/olMap/services/StyleService.js
src/modules/olMap/utils/olStyleUtils.js
test/modules/olMap/handler/draw/OlDrawHandler.test.js
test/modules/olMap/services/StyleService.test.js
test/modules/olMap/util/olStyleUtils.test.js

- remove necessary methods `getStyleFunction`, `getFeatureStyleFunction`
...and also:
- refactor usage of **_olStyleUtil_** methods
- rename/refine **_olStyleUtil_** method names

refactor StyleService

---

src/modules/olMap/overlayStyle/MeasurementOverlayStyle.js
src/modules/olMap/services/OverlayService.js
test/modules/olMap/overlayStyle/MeasurementOverlayStyle.test.js
test/modules/olMap/services/OverlayService.test.js

cherry pick from (#3087)
handle empty overlays property correctly

MeasurementOverlayStyle: handle empty overlays property correctly

---

karma.conf.single.js

```js
npm run test:single --spec=queryParameters
```
is the same now as
```js
npm run test:single --spec=queryParameters.test.js
```

simplify single test file specification

---

src/modules/olMap/formats/kml.js
src/modules/olMap/handler/routing/OlRoutingHandler.js
test/modules/olMap/formats/kml.test.js
test/modules/olMap/handler/routing/OlRoutingHandler.test.js

This reverts commit 4acaa589aa1e2a06050f1ee5ca712a3759372af3.
Fixes #3137

v4.4: Revert "RoutingStyle: prevent rendering of large icons (#3113) (#3118)"

---

src/modules/chips/components/assistChips/ShareChip.js
src/modules/toolbox/components/shareToolContent/ShareToolContent.js
test/modules/chips/components/ShareChip.test.js
test/modules/toolbox/components/shareToolContent/ShareToolContent.test.js

refactor share-api usage to use fallback dialog instead of warning notification

ShareApi: use fallback dialog (v4.4)

---

src/modules/search/components/menu/types/location/LocationResultItem.js
test/modules/search/components/menu/types/location/LocationResultItem.test.js

Adjust the zoom level for coordinates to common viewers (e.g., Google Maps, ...). So far, we've zoomed in a bit too far.

LocationResultItem: update max zoom level
