ldbv-by/bav4

- package-lock.json
- package.json
- src/components/contextMenue/ContextMenue.js
- src/components/contextMenue/contextMenue.css
- src/components/contextMenue/index.js
- src/components/contextMenue/store/contextMenue.action.js
- src/components/contextMenue/store/contextMenue.reducer.js
- src/components/map/OlMap.js
- src/index.html
- src/main.js
- src/store/StoreService.js
- test/components/contextMenue/ContextMenue.test.js
Adds a context-menue component
> Dev context menue

- README.md
- karma.conf.js
- karma.conf.travis.js
- package-lock.json
- package.json
... and visualize code coverage
> Integrate coveralls

- README.md
- src/modules/map/i18n/index.js
- src/modules/map/i18n/map.provider.js
- src/modules/map/index.js
- src/modules/uiTheme/i18n/index.js
- src/modules/uiTheme/i18n/uiTheme.provider.js
- src/modules/uiTheme/index.js
- src/services/TranslationService.js
- test/modules/map/i18n/map.provider.test.js
- test/modules/uiTheme/i18n/uiTheme.provider.test.js
- test/service/TranslationService.test.js
Each module registers its own i18n provider at the TranslationService
> refactor i18n setup

- src/main.css
- src/modules/commons/components/toggle/Toggle.js
- src/modules/commons/components/toggle/toggle.css
- test/modules/commons/components/Toggle.test.js
Introduce a secondary color and use it within the toggle component
> introduce a secondary color

- src/modules/header/components/Header.js
- src/modules/modal/components/modal.css
Sorry, I should have better done that within the review.
Contains just suggestions ....
> Slightly improve text and layout

- src/modules/contextMenue/components/ContextMenue.js
- src/modules/contextMenue/components/contextMenue.css
- test/modules/contextMenue/components/ContextMenue.test.js
Coming back to the start of my lit-html learning-curve :) 
...and refactor this component for a cleaner lit-html approach.
> update contextmenue with more litify usage

- src/modules/header/components/Header.js
- src/modules/utils/components/showCase/ShowCase.js
- src/modules/utils/components/showCase/index.js
- src/modules/utils/index.js
- test/modules/header/components/Header.test.js
- test/modules/utils/components/showCase/showCase.test.js
as mentioned last week, moving the code of showcase content to a separate component.
Due to unfinished/unsolved test as draft...
> move showcase content to single component

- src/modules/commons/components/toggle/Toggle.js
> fix: Toogle.js does not work on Chrome and Webkit (#51)

- .eslintrc.js
- package-lock.json
- src/modules/iframe/components/NonEmbeddedHint.js
- src/modules/search/components/AutocompleteSearch.js
- test/modules/modal/components/Modal.test.js
EsLint rule for type-safe equality operators.
> EsLint rule for type-safe equality operators

- src/modules/modal/components/modal.css
- src/modules/utils/components/showCase/ShowCase.js
To handle large content in modal-component, css-style is updated.
Additional Test-Content ("Lorem ipsum") will be removed before merge with master.
> prevent outer scrollbars if modal content to large

- src/modules/commons/components/icon/Icon.js
- src/modules/commons/components/icon/icon.css
- src/modules/commons/components/icon/index.js
- src/modules/commons/index.js
- src/modules/utils/components/showCase/ShowCase.js
- src/modules/utils/components/showCase/assets/arrow-up.svg
- src/modules/utils/components/showCase/assets/list.svg
- test/modules/commons/components/Icon.test.js
- test/modules/utils/components/showCase/ShowCase.test.js
Clickable icon component, The svg graphic can be configured via the `icon` attribute / property.
This is not a replacement for the icon-button, which we will need at a later moment.
> Clickable Icon

- src/modules/modal/components/modal.css
- src/modules/utils/components/showCase/ShowCase.js
update max-height value for modal-component, to prevent unreachable content
remove unnecessary 'Lorem ipsum' content from showCase
> update css and remove unnecessary showcase-code

- src/modules/map/components/olMap/OlMap.js
- test/modules/map/components/olMap/OlMap.test.js
Refactoring of the internal  view synchronization, We nee this for #71 and #69
> Refactor map sync view

- src/injection/config.js
- src/modules/search/services/provider/searchResult.provider.js
- src/services/provider/geoResource.provider.js
- test/modules/search/services/provider/searchResult.provider.test.js
- test/service/GeoResourceService.test.js
- test/service/provider/geoResource.provider.test.js
Provider should have their own folder under `/services`
> Refactor provider

- src/modules/map/components/olMap/olMapUtils.js
- src/modules/map/components/olMap/utils/feature.provider.js
- src/services/UrlService.js
- test/modules/map/components/olMap/olMapUtils.test.js
- test/modules/map/components/olMap/util/feature.provider.test.js
- test/service/UrlService.test.js
Load vector georesources over http
> Dev vector geo resources

- .eslintrc.js
- src/modules/commons/components/button/Button.js
- src/modules/commons/components/popup/Popup.js
- src/modules/contextMenue/components/ContextMenue.js
- src/modules/map/components/infoButton/InfoButton.js
- src/modules/map/components/layerManager/LayerItem.js
- src/modules/map/components/layerManager/LayerManager.js
- test/modules/commons/components/Popup.test.js
Add and apply a rule for keyword spacing
> Quality add keyword spacing rule

- src/modules/map/components/zoomButtons/zoomToExtentButton.css
> fix: Zoom2Extent Button

- src/services/MapService.js
- src/services/provider/mapDefinitions.provider.js
- test/service/MapService.test.js
- test/service/provider/mapDefinitions.provider.test.js
We need this PR for displaying coordinate information in footer and context-menue.
> Revise service and provider for map related meta data

- src/modules/map/components/olMap/handler/contextMenu/OlMapContextMenuContent.js
- src/services/provider/mapDefinitions.provider.js
- test/modules/map/components/olMap/handler/contextMenu/OlMapContextMenuContent.test.js
- test/service/provider/mapDefinitions.provider.test.js
> Round WGS84 coordinates to 5 decimal places

- src/modules/map/components/contextMenu/MapContextMenu.js
- src/modules/map/components/contextMenu/mapContextMenu.css
- test/modules/map/components/contextMenu/MapContextMenu.test.js
Re-implementation of the positioning mechanism of the `MapContextMenu`. Fixes #94 .
> Fix wrong positioning on first click events

- package-lock.json
- package.json
- webpack.config.js
> Migrate to webpack-cli 4.5.0

- .eslintrc.js
- src/injection/config.js
- src/injection/core/utils.js
- src/injection/index.js
- src/modules/commons/components/popup/Popup.js
- src/modules/contextMenue/components/ContextMenue.js
- src/modules/map/components/infoButton/InfoButton.js
- src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
- src/modules/search/components/AutocompleteSearch.js
- src/services/EnvironmentService.js
- test/injection/core/classInjection.js
- test/injection/core/functionInjection.test.js
- test/injection/core/multipleRegister.test.js
- test/injection/core/newInstanceInjection.test.js
- test/injection/core/prototypeInjection.test.js
- test/injection/core/testsConfig.js
- test/modules/map/components/layerManager/LayerItem.test.js
- test/modules/map/components/layerManager/LayerManager.test.js
- test/modules/map/components/olMap/handler/measure/MeasurementOverlay.test.js
- test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
- test/modules/map/components/olMap/olMapUtils.test.js
- test/service/EnvironmentService.test.js
see:
- https://eslint.org/docs/rules/no-var
- https://eslint.org/docs/rules/prefer-const
> Add eslint no-var & prefer-const rule

- test/modules/menue/components/sidePanel/SidePanel.test.js
move testcase to folder to reflect location of ClassUnderTest 'SidePanel.js'
> move testcase to folder

- src/injection/config.js
- src/injection/core/injector.js
- src/services/StoreService.js
- test/injection/core/Injector.test.js
When injector is marked as ready, all dependencies are registered and resolvable.
> Add information about readiness of injector

- src/utils/checks.js
- src/utils/numberUtils.js
- test/utils/checks.test.js
Just the first checks, more to come ...
> Checks for common types

- src/modules/map/store/GeolocationObserver.js
- test/modules/map/store/GeolocationObserver.test.js
... in case of watch id is `0`
> Geolocation can not be deactivated

- src/modules/map/components/layerManager/LayerManager.js
- test/modules/map/components/layerManager/LayerManager.test.js
fix issue Layer visibility toggle in layer manager #152 with a recognition
of the visibility-property on load
add test for the issue
> fix #152: recognize layer-properties on load

- src/modules/map/store/LayersObserver.js
- src/services/domain/topic.js
- src/services/provider/topics.provider.js
- test/service/domain/topic.test.js
- test/service/provider/topics.provider.test.js
> Rename topics fields again

- src/modules/contextMenue/components/ContextMenue.js
- src/modules/footer/components/coordinateSelect/CoordinateSelect.js
- src/modules/header/components/Header.js
- src/modules/map/components/contextMenu/MapContextMenu.js
- src/modules/map/components/geolocationButton/GeolocationButton.js
- src/modules/map/components/infoButton/InfoButton.js
- src/modules/map/components/layerManager/LayerManager.js
- src/modules/map/components/olMap/OlMap.js
- src/modules/menue/components/sidePanel/SidePanel.js
- src/modules/modal/components/Modal.js
- src/modules/uiTheme/components/provider/ThemeProvider.js
- src/modules/uiTheme/components/toggle/ThemeToggle.js
`extractState` does take a state not the store object
> Correct argument name

- src/modules/footer/components/Footer.js
- src/modules/header/components/Header.js
- src/modules/menu/components/contentPanel/ContentPanel.js
- src/modules/menu/components/mediaQueryPanel/MediaQueryPanel.js
- src/modules/menu/components/toolBox/ToolBox.js
it's a state object not the store itself
> Correct name of argument

- src/utils/sleep.js
- test/utils/sleep.test.js
Primarily thought for simulating delayed responses, e.g. from of backend endpoints
> Helper function for delaying an execution

- src/modules/map/components/olMap/handler/measure/GeometryUtils.js
- test/modules/map/components/olMap/handler/measure/GeometryUtils.test.js
Fix the flickering of the overlay
Add tests for the utility methods getFormattedLength and getFormattedArea
> fix for #197

- src/modules/map/components/olMap/utils/feature.provider.js
- src/modules/search/services/provider/searchResult.provider.js
- src/services/HttpService.js
- src/services/UrlService.js
- src/services/provider/administration.provider.js
- src/services/provider/altitude.provider.js
- src/services/provider/geoResource.provider.js
- src/services/provider/topics.provider.js
- src/services/provider/urlShorteningProvider.js
- test/modules/map/components/olMap/util/feature.provider.test.js
- test/modules/search/services/provider/searchResult.provider.test.js
- test/service/HttpService.test.js
- test/service/UrlService.test.js
- test/service/provider/administration.provider.test.js
- test/service/provider/altitude.provider.test.js
- test/service/provider/geoResource.provider.test.js
- test/service/provider/topics.provider.test.js
- test/service/provider/urlShortening.provider.test.js
...added some convenience method for GET, POST, HEAD
> Extend http-service methods

- src/modules/map/components/olMap/OlMap.js
- test/modules/map/components/olMap/OlMap.test.js
...should be done only in `LayersPlugin.js`
> Remove georesource service initialisation in olMap

- src/injection/config.js
- src/modules/header/components/Header.js
- src/modules/header/components/header.css
- src/services/HttpService.js
- src/services/StoreService.js
- src/store/network.action.js
- src/store/network.reducer.js
- test/modules/header/components/Header.test.js
- test/modules/map/components/olMap/OlMap.test.js
- test/modules/map/components/olMap/olMapUtils.test.js
- test/modules/map/store/ContextClickPlugin.test.js
- test/modules/map/store/layers.reducer.test.js
- test/modules/menu/components/contentPanel/ContentPanel.test.js
- test/modules/menu/components/sidePanel/SidePanel.test.js
- test/modules/menu/components/toolBar/ToolBar.test.js
- test/service/HttpService.test.js
- test/service/StoreService.test.js
- test/service/provider/proj4.provider.test.js
- test/service/provider/proxifyUrl.provider.test.js
- test/service/provider/stringifyCoords.provider.test.js
- test/store/network.reducer.test.js
- adds a network-related slice of state
- intercepts fetch calls to update networks fetching property
- animates BA logo while fetching
- remove double 'it' expressions in tests
> Add network related state

- src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
update order of cleaning-operations (unregister etc.) to ensure
that measure-statistics in store a reseted correctly
> fix reset stats on deactivate

- src/index.html
- src/modules/menu/components/mainMenu/MainMenu.js
- src/modules/utils/components/devInfo/DevInfo.js
- src/modules/utils/components/devInfo/devInfo.css
- test/modules/menu/components/mainMenu/MainMenu.test.js
- test/modules/utils/components/devInfo/DevInfo.test.js
Found a better place for the `DevInfo` component...
> Move dev info to main menu

- src/modules/map/store/MeasurementPlugin.js
> Improve doc of measurement plugin

- src/modules/map/components/olMap/OlMap.js
- src/modules/map/store/layers.action.js
- src/modules/map/store/layers.reducer.js
- test/modules/map/store/layers.reducer.test.js
previously: layer to geoResource 1:1 
now: layer to geoResource n:1
> Allow multiple layer for same geoResource

- src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
- test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
fix bug, which prevents the fullqualified layer (as georesource
but with temporaryId) to be added to Layers
add test for bug
> fix persisting measurement-layer

- src/modules/utils/components/devInfo/devInfo.css
fixes #246  devInfo,  change positon to absolute
> fix: removed fixed posion

- src/modules/menu/components/mainMenu/mainMenu.css
> fix: height transform

- src/modules/baElement.css
custom Scrollbar not working in Firefox
> add: custom scrollbar

- test/modules/toolbox/components/toolContainer/ToolContainer.test.js
> add test to for ToolContainer:_deactivateByContentId

- src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
- src/modules/map/store/MeasurementPlugin.js
- test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
add feature-id generation based on tool-id
> add feature-id generation

- src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
- src/modules/map/components/olMap/handler/measure/OverlayManager.js
- test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
move feature-id generation to drawstart-event,
remove id-setting in OverlayManager
add, update tests
> fixes #281

- src/modules/menu/components/mainMenu/content/AbstractContentPanel.js
- src/modules/menu/components/mainMenu/content/abstractContentPanel.css
- test/modules/menu/components/mainMenu/content/AbstractContentPanel.test.js
Existing content panels will have to inherit from that class.
> Provide a common CSS class for all content panels

- src/services/HttpService.js
- src/store/network/network.reducer.js
- test/modules/header/components/Header.test.js
- test/service/HttpService.test.js
- test/store/network/network.reducer.test.js
...take pending requests into account
> Extend network store

- src/modules/map/components/olMap/services/LayerService.js
- test/modules/map/components/olMap/services/LayerService.test.js
> Update network state when ol sources are fetching data

- src/modules/map/components/geolocationButton/assets/geo-alt-fill.svg
- src/modules/map/components/geolocationButton/assets/vinyl.svg
- src/modules/map/components/geolocationButton/geolocationButton.css
- src/modules/map/components/olMap/OlMap.js
- test/modules/map/components/olMap/OlMap.test.js
- finetune PinchRotate behavior
- replace geolocation icon
> Improve map related UX

- src/modules/toolbox/components/toolContainer/ToolContainer.js
- test/modules/toolbox/components/toolContainer/ToolContainer.test.js
fixes Window resize triggers unindended call of removeLayer() #303
> update ToolContent-Behavior on createView

- src/modules/BaElement.js
- test/modules/BaElement.test.js
> BaElement: open updateState()

- src/modules/commons/components/checkbox/Checkbox.js
- src/modules/commons/components/toggle/Toggle.js
fixes #307,
for further information see:
-  https://stackoverflow.com/questions/55962214/litelement-not-updating-checkbox-in-list#answers
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#checked
> Use a property (instead of attribute) for "checked"  binding

- src/modules/header/components/Header.js
- src/modules/header/i18n/header.provider.js
- test/modules/header/components/Header.test.js
- test/modules/header/i18n/header.provider.test.js
fix Missing i18n in header #321
> add i18n for tab-titles in header

- src/modules/map/components/layerManager/layerManager.css
Fix drag&drop in LayerManager #322
> Fix drag&drop in LayerManager by add padding to placeholder-style

- src/services/UrlService.js
> Improve comment for UrlService#shorten

- src/modules/BaElement.js
- src/modules/header/components/Header.js
- src/modules/modal/components/Modal.js
- src/modules/modal/store/modal.action.js
- src/modules/modal/store/modal.reducer.js
- test/modules/BaElement.test.js
- test/modules/header/components/Header.test.js
- test/modules/modal/components/Modal.test.js
- test/modules/modal/store/modal.action.test.js
- test/modules/modal/store/modal.reducer.test.js
We don't want to mess the state with a lit-html TemplateResult.
> Rework modal element

- src/modules/header/components/Header.js
- test/modules/header/components/Header.test.js
> Fix showcase integration

- src/modules/map/components/olMap/services/StyleService.js
- test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
- test/modules/map/components/olMap/services/StyleService.test.js
fixes #332 - Measurement: Labeling seems not to be
working always correctly
> add styling entrypoint for old measure-features

- src/main.css
> change z-index

- src/index.html
- src/modules/header/components/Header.js
- src/modules/menu/components/mainMenu/MainMenu.js
- src/modules/menu/components/mainMenu/mainMenu.css
- src/store/media/media.action.js
- src/store/media/media.reducer.js
- test/modules/header/components/Header.test.js
- test/modules/menu/components/mainMenu/MainMenu.test.js
- test/store/media/media.reducer.test.js
> Fix Virtual Keyboard problem

- src/modules/header/components/Header.js
- src/modules/header/components/header.css
- src/modules/menu/components/mainMenu/mainMenu.css
> fix: zindx emblem, close button tablet, focus

- src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
- test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
> Fix flaky tests caused by debounced method

- src/modules/layerManager/components/LayerItem.js
- src/modules/layerManager/components/LayerManager.js
- src/modules/layerManager/i18n/layerManager.provider.js
- src/modules/layerManager/index.js
- test/modules/layerManager/components/LayerItem.test.js
- test/modules/layerManager/components/LayerManager.test.js
- test/modules/layerManager/i18n/layerManager.provider.test.js
fix missing i18n-support in module layerManager with import-statement,
rename i18n-key to follow naming convention
> fix LayerManager i18n

- src/modules/toolbox/components/measureToolContent/MeasureToolContent.js
Works with lit-html 1.x, but has to be fixed for lit 2.0
> Fix property and event-listener bindings

- src/modules/map/components/contextMenu/MapContextMenuContent.js
- test/modules/map/components/contextMenu/MapContextMenuContent.test.js
and revert icon modification as visual feedback
> Use stringified coords for copying

- src/modules/MvuElement.js
- src/modules/map/components/olMap/OlMap.js
- test/modules/MvuElement.test.js
- test/modules/map/components/olMap/OlMap.test.js
additionally:
- added method `#observeModel` to  `MvuElement`
- ported `OlMap` to `MvuElement`
> Add a single-click handler on OlMap

- README.md
- package.json
> Make script start:nohostcheck work again

- src/modules/header/components/Header.js
- src/modules/header/components/header.css
- src/modules/search/components/menu/types/geoResource/GeoResourceResultsPanel.js
- src/modules/search/components/menu/types/geoResource/geoResourceResultsPanel.css
- src/modules/search/components/menu/types/location/LocationResultsPanel.js
- src/modules/search/components/menu/types/location/locationResultsPanel.css
- src/modules/search/i18n/search.provider.js
- test/modules/header/components/Header.test.js
- test/modules/search/components/menu/types/geoResource/GeoResourceResultsPanel.test.js
- test/modules/search/components/menu/types/location/LocationResultsPanel.test.js
- test/modules/search/i18n/search.provider.test.js
Thx to @alsturm :
- limit result item size and make them expandable
- add a button to the Header input field to clear the entry
> Optimize Search UI

- src/modules/MvuElement.js
- test/utils/storeUtils.test.js
...and improve docs of `MvuElement`
> Add test for arrays

- src/modules/map/components/olMap/olStyleUtils.js
- src/services/domain/styles.js
- src/store/draw/draw.action.js
- test/modules/map/components/olMap/olStyleUtils.test.js
- test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js
- test/service/domain/styles.test.js
updating StyleSizeTypes-Key from 'BIG' to 'LARGE'
> fix StyleSizeTypes-Key to 'large'

- src/modules/map/components/olMap/OlMap.js
- src/modules/map/components/olMap/handler/OlLayerHandler.js
- src/modules/map/components/olMap/handler/highlight/OlHighlightLayerHandler.js
- test/modules/map/components/olMap/OlMap.test.js
- test/modules/map/components/olMap/handler/OlLayerHandler.test.js
- test/modules/map/components/olMap/handler/highlight/OlHighlightLayerHandler.test.js
to enable/disable default click and context-click handling.
Fixes #516.
> make OlLayerHandler configurable

- src/modules/modal/assets/arrowLeftShort.svg
- src/modules/modal/components/Modal.js
- src/modules/modal/components/modal.css
- test/modules/modal/components/Modal.test.js
>  improve mobile layout for Modal component

- src/modules/toolbox/components/drawToolContent/DrawToolContent.js
- src/modules/toolbox/components/measureToolContent/MeasureToolContent.js
- src/modules/toolbox/components/toolContainer/AbstractToolContent.js
- test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js
- test/modules/toolbox/components/measureToolContent/MeasureToolContent.test.js
as preparation for future work on local states in `DrawToolContent.js` and `MeasureToolContent.js` we update  to MvuElement
> update AbstractToolContent to MvuElement

- src/modules/featureInfo/components/FeatureInfoPanel.js
- src/modules/map/components/contextMenu/mapContextMenu.css
- src/modules/map/components/contextMenu/mapContextMenuContent.css
- src/plugins/FeatureInfoPlugin.js
- src/plugins/MainMenuPlugin.js
- src/store/featureInfo/featureInfo.action.js
- src/store/featureInfo/featureInfo.reducer.js
- test/modules/map/components/olMap/handler/featureInfo/OlFeatureInfoHandler.test.js
- test/plugins/FeatureInfoPlugin.test.js
- test/plugins/MainMenuPlugin.test.js
- test/store/featureInfo/featureInfo.reducer.test.js
Add a possibility detecting all async FeatureInfo requests are resolved (successfully or not).
> improve feature info request management

- src/modules/map/components/olMap/handler/featureInfo/OlFeatureInfoHandler.js
- test/modules/map/components/olMap/handler/featureInfo/OlFeatureInfoHandler.test.js
It is now guaranteed that the highlight animation runs at least 300ms.
@thiloSchlemmer Thanks for your helpful feedback
> optimize highlight animation duration

- test/modules/map/components/olMap/handler/featureInfo/OlFeatureInfoHandler.test.js
increase also delay of postrender execution
> prevent flakiness in OlFeatureInfoHandler (2)

- src/modules/toolbox/index.js
> reorder Toolbar-imports to load translation first

- src/modules/map/components/olMap/handler/draw/OlDrawHandler.js
- src/modules/map/components/olMap/olStyleUtils.js
- src/modules/toolbox/components/drawToolContent/DrawToolContent.js
- test/modules/map/components/olMap/handler/draw/OlDrawHandler.test.js
- test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
- test/modules/map/components/olMap/olStyleUtils.test.js
update select- and modify-StyleFunction to use the feature-color for styling in
favor of a default color
@alsturm: any further suggestions for styleProperties appreciated
> using FeatureColor in styleFunctions (if possible)

- src/modules/map/components/olMap/OlMap.js
- src/modules/map/components/olMap/olMapUtils.js
- test/modules/map/components/olMap/OlMap.test.js
- test/modules/map/components/olMap/handler/draw/OlDrawHandler.test.js
- test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
- test/modules/map/components/olMap/mapTestUtils.js
- test/modules/map/components/olMap/olMapUtils.test.js
regarding touch ("short-press") and long-press events
> rework event handling for touch devices

- src/modules/featureInfo/components/FeatureInfoPanel.js
- src/modules/featureInfo/components/featureInfoPanel.css
- test/modules/featureInfo/components/FeatureInfoPanel.test.js
- in portrait mode the table is desplayed as a colum.
> add: portrait css, links word break

- src/modules/map/components/olMap/handler/draw/OlDrawHandler.js
- src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
- src/modules/map/components/olMap/services/InteractionStorageService.js
- src/modules/map/components/olMap/services/MeasurementStorageService.js
- src/modules/map/i18n/olMap.provider.js
- src/modules/map/injection/index.js
- src/modules/toolbox/components/drawToolContent/DrawToolContent.js
- src/modules/toolbox/components/measureToolContent/MeasureToolContent.js
- src/services/StoreService.js
- src/store/draw/draw.action.js
- src/store/shared/shared.action.js
- src/store/shared/shared.reducer.js
- test/modules/map/components/olMap/handler/draw/OlDrawHandler.test.js
- test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
- test/modules/map/components/olMap/services/MeasurementStorageService.test.js
- test/modules/map/i18n/olMap.provider.test.js
- test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js
- test/modules/toolbox/components/measureToolContent/MeasureToolContent.test.js
- test/modules/toolbox/components/toolContainer/ToolContainer.test.js
- test/service/StoreService.test.js
- test/store/shared/shared.reducer.test.js
add a new slice of store for data, which is used (read) from multiple components
> add shared-data slice in store

- src/main.css
- src/modules/geoResourceInfo/assets/boxarrowupright.svg
- src/modules/geoResourceInfo/assets/placeholder.svg
- src/modules/geoResourceInfo/components/GeoResourceInfoPanel.js
- src/modules/geoResourceInfo/components/geoResourceInfoPanel.css
- src/modules/modal/components/modal.css
- test/modules/geoResourceInfo/components/GeoResourceInfoPanel.test.js
add responsive style for layerinfo.
> Enhancement layerinfo style

- src/modules/header/components/Header.js
- src/modules/menu/components/mainMenu/MainMenu.js
- src/modules/search/components/menu/types/geoResource/GeoResourceResultItem.js
- src/plugins/HighlightPlugin.js
- src/plugins/MainMenuPlugin.js
- src/store/mainMenu/mainMenu.action.js
- src/store/mainMenu/mainMenu.reducer.js
- test/modules/header/components/Header.test.js
- test/modules/menu/components/mainMenu/MainMenu.test.js
- test/modules/search/components/menu/types/geoResource/GeoResourceResultItem.test.js
- test/plugins/FeatureInfoPlugin.test.js
- test/plugins/HighlightPlugin.test.js
- test/plugins/MainMenuPlugin.test.js
- test/store/mainMenu/mainMenu.action.test.js
- test/store/mainMenu/mainMenu.reducer.test.js
- tabs are referenced by a String now
- MainMenu: remove unnecessary MainMenuTabIndex enum
- rename mainMenu actions
> refactor MainMenu and mainMenu.reducer

- src/modules/header/components/Header.js
- src/modules/menu/components/mainMenu/MainMenu.js
- src/modules/search/components/menu/types/geoResource/GeoResourceResultItem.js
- src/plugins/HighlightPlugin.js
- src/plugins/MainMenuPlugin.js
- src/store/mainMenu/mainMenu.action.js
- src/store/mainMenu/mainMenu.reducer.js
- test/modules/header/components/Header.test.js
- test/modules/menu/components/mainMenu/MainMenu.test.js
- test/modules/search/components/menu/types/geoResource/GeoResourceResultItem.test.js
- test/plugins/FeatureInfoPlugin.test.js
- test/plugins/HighlightPlugin.test.js
- test/plugins/MainMenuPlugin.test.js
- test/store/mainMenu/mainMenu.action.test.js
- test/store/mainMenu/mainMenu.reducer.test.js
A better name would be  "TabId"
> rename tab enum

- src/modules/map/components/olMap/handler/draw/OlDrawHandler.js
- src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
- src/store/draw/draw.action.js
- src/store/draw/draw.reducer.js
- src/store/measurement/measurement.action.js
- src/store/measurement/measurement.reducer.js
- test/modules/map/components/olMap/handler/draw/OlDrawHandler.test.js
- test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
- test/modules/map/components/olMap/olStyleUtils.test.js
adding the behavior to switch the tool (measureTool, drawTool) by selecting the corresponding feature.
> Update select-behavior in interaction-tools

- src/modules/commons/components/button/Button.js
- src/modules/commons/components/checkbox/Checkbox.js
- src/modules/commons/components/icon/Icon.js
- src/modules/commons/components/toggle/Toggle.js
- src/modules/toolbox/components/drawToolContent/drawToolContent.css
- src/modules/topics/components/menu/catalog/CatalogLeaf.js
- src/utils/markup.js
- test/modules/commons/components/Button.test.js
- test/modules/commons/components/Checkbox.test.js
- test/modules/commons/components/Icon.test.js
- test/modules/commons/components/Toggle.test.js
- test/modules/header/components/Header.test.js
- test/modules/layerManager/components/LayerItem.test.js
- test/modules/layerManager/components/LayerManager.test.js
- test/modules/topics/components/menu/TopicsContentPanel.test.js
- test/modules/topics/components/menu/catalog/CatalogLeaf.test.js
- test/modules/topics/components/menu/catalog/CatalogNode.test.js
- test/utils/markup.test.js
by handling nested MvuElements like normal elements.
> improve test id stability

- src/plugins/LayersPlugin.js
- test/plugins/LayersPlugin.test.js
> handle missing layer id in query parameter

- src/services/provider/stringifyCoords.provider.js
- test/service/provider/stringifyCoords.provider.test.js
> update formatting for 4326-coordinates

- src/services/provider/sourceType.provider.js
- test/service/provider/sourceType.provider.test.js
> sourcetype provider: encode url parameter

- src/plugins/FeatureInfoPlugin.js
- test/plugins/FeatureInfoPlugin.test.js
add abort-behavior in FeatureInfoPlugin on changes of tool.current property
> FeatureInfoPlugin: close on tool-change

- src/services/domain/geoResources.js
- src/services/provider/geoResource.provider.js
- test/service/domain/geoResources.test.js
- test/service/provider/geoResource.provider.test.js
> remove "background" property

- src/modules/map/components/olMap/services/VectorLayerService.js
- test/modules/map/components/olMap/services/VectorLayerService.test.js
> update the geoResource's label asynchronously

- src/modules/menu/components/mainMenu/mainMenu.css
disable slider range in firefox
> add: pointer-events

- src/plugins/ContextClickPlugin.js
- test/plugins/ContextClickPlugin.test.js
> clear context notification on touch devices

- src/plugins/FeatureInfoPlugin.js
- test/plugins/FeatureInfoPlugin.test.js
> prevent (almost) simultaneous feature info requests

- src/store/layers/layers.reducer.js
- test/store/layers/layers.reducer.test.js
> fix: 'alwaysTop'  does not have an impact when adding layers

- src/modules/map/components/olMap/olStyleUtils.js
on displays with higher resolution the line-segments for the subticks are not properly moved parallel.
This branch takes the pixelRatio into account and creates a correct line-segment.
> Enhancement ruler style pixel ratio

- src/modules/map/components/olMap/handler/geolocation/OlGeolocationHandler.js
- test/modules/map/components/olMap/handler/geolocation/OlGeolocationHandler.test.js
> OlGeolocationHandler: don't prevent default click handler 

- src/services/MapService.js
- test/service/MapService.test.js
> adjust rotation threshold

- src/plugins/LayersPlugin.js
- test/plugins/LayersPlugin.test.js
> process multiple occurrence of same  id in query parameters

- src/modules/map/components/olMap/OlMap.js
- src/modules/map/components/olMap/services/LayerService.js
- test/modules/map/components/olMap/OlMap.test.js
- test/modules/map/components/olMap/services/LayerService.test.js
use new loadstart/loadend events from ol.map (available since v6.14)
> use  loadstart/loadend events from ol.map

- src/modules/menu/components/mainMenu/MainMenu.js
- test/modules/menu/components/mainMenu/MainMenu.test.js
> fix MainMenu model

- src/modules/layerManager/components/LayerItem.js
- test/modules/layerManager/components/LayerItem.test.js
correct use of geoResourceId
explicitly set geoResourcesId for cloning
default layer-value in model is null
fixes LayerItem #840
> fix LayerItem

- src/modules/footer/components/baseLayerInfo/BaseLayerInfo.js
- src/modules/map/components/attributionInfo/AttributionInfo.js
- test/modules/footer/components/baseLayerInfo/BaseLayerInfo.test.js
- test/modules/map/components/attributionInfo/AttributionInfo.test.js
> Fix usage of geoResourceId

- src/modules/map/components/attributionInfo/AttributionInfo.js
- src/services/domain/geoResources.js
- src/services/provider/attribution.provider.js
- test/modules/map/components/attributionInfo/AttributionInfo.test.js
- test/service/provider/attribution.provider.test.js
> Fix attribution info

- src/plugins/HighlightPlugin.js
- test/plugins/HighlightPlugin.test.js
> remove search related highlight features when query is empty

- src/main.js
- src/utils/markup.js
- test/e2e/windowProperties.spec.js
- test/utils/markup.test.js
affecting lazily initialized components.
fixes #867
> fix broken test id generation

- src/plugins/MainMenuPlugin.js
- src/services/domain/queryParameters.js
- src/store/mainMenu/mainMenu.action.js
- src/store/mainMenu/mainMenu.reducer.js
- test/plugins/MainMenuPlugin.test.js
- test/service/domain/queryParameters.test.js
- test/store/mainMenu/mainMenu.action.test.js
- test/store/mainMenu/mainMenu.reducer.test.js
defining the initially shown tab of the main menu.
Example: http://localhost:8080/?mid=1 opens the "Map" tab
> add query parameter "mid"

- src/modules/map/components/olMap/services/VectorLayerService.js
- test/modules/map/components/olMap/services/VectorLayerService.test.js
... as a starting point for further development e.g. loading existing features within an OlLayerHandler
> provide also the geoResourceId as a property of the ol layer

- src/store/layers/layers.reducer.js
- test/store/layers/layers.reducer.test.js
fixes  #883
@thiloSchlemmer Thx for analyzing this bug
> ensure complete list of default layer properties

- src/modules/search/services/provider/searchResult.provider.js
- test/modules/search/services/provider/searchResult.provider.test.js
affecting all SearchResult providers.
Credits @AlanNaum
> fix missing slash replacement and query string encoding

- src/modules/map/components/olMap/handler/draw/OlDrawHandler.js
- src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
- src/modules/toolbox/components/drawToolContent/DrawToolContent.js
- src/services/ShareService.js
- test/modules/map/components/olMap/handler/draw/OlDrawHandler.test.js
- test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
- test/service/ShareService.test.js
fixes bug where drawings, which are shared as "share to collaborate", were not editable anymore
> Fix edit of shared drawings

- src/modules/map/components/olMap/handler/draw/OlDrawHandler.js
> Fix ol draw handler delete point on click

- src/main.css
- src/modules/menu/components/mainMenu/mainMenu.css
add overscroll-behavior to body
> fixes #906

- src/modules/toolbox/components/toolBar/toolBar.css
> change toolbar-button position from absolute to fixed

- src/modules/map/components/olMap/handler/draw/OlDrawHandler.js
- src/modules/map/components/olMap/handler/measure/OlMeasurementHandler.js
- test/modules/map/components/olMap/handler/draw/OlDrawHandler.test.js
- test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
> fix add/remove of EventListeners

- src/modules/map/components/olMap/handler/draw/OlDrawHandler.js
- src/modules/map/components/olMap/olStyleUtils.js
- src/modules/map/i18n/olMap.provider.js
- src/modules/toolbox/components/drawToolContent/DrawToolContent.js
- test/modules/map/components/olMap/handler/draw/OlDrawHandler.test.js
- test/modules/map/components/olMap/olStyleUtils.test.js
- test/modules/map/i18n/olMap.provider.test.js
- test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js
> update text-input, prevent DefaultText

- src/modules/toolbox/components/toolContainer/abstractToolContent.css
Removed the opacity to fix it... added some margin.
> fix style properties of subtext

- src/modules/footer/components/baseLayerInfo/BaseLayerInfo.js
- src/services/provider/geoResource.provider.js
- test/modules/footer/components/baseLayerInfo/BaseLayerInfo.test.js
- test/service/provider/geoResource.provider.test.js
especially when a GeoResources owns  "extended" attributions
> optimize attribution handling

- src/modules/map/components/olMap/handler/featureInfo/OlFeatureInfoHandler.js
- src/plugins/FeatureInfoPlugin.js
- test/modules/map/components/olMap/handler/featureInfo/OlFeatureInfoHandler.test.js
> fix broken olFeatureInfoHandler

- src/modules/toolbox/components/measureToolContent/MeasureToolContent.js
- src/utils/markup.js
- test/modules/toolbox/components/measureToolContent/MeasureToolContent.test.js
- test/utils/markup.test.js
> update creation of copyToClipboard-value

- src/modules/map/components/olMap/handler/draw/OlDrawHandler.js
- src/modules/toolbox/components/drawToolContent/DrawToolContent.js
- test/modules/map/components/olMap/handler/draw/OlDrawHandler.test.js
- test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js
> update initialization for DrawTypes & DefaultText

- src/modules/toolbox/components/importToolContent/ImportToolContent.js
- test/modules/toolbox/components/importToolContent/ImportToolContent.test.js
update event-trigger to input-label
fixes #904
> fix trigger to clear input.value in ImportToolContent

- src/modules/featureInfo/components/featureInfoPanel.css
> changed display property of td tag 

- src/modules/header/components/header.css
> always show full emblem

- src/modules/menu/components/mainMenu/assets/chevron-right-small.svg
- src/modules/menu/components/mainMenu/mainMenu.css
- changed icon
- centered it 
- fixed wrong icon (see below)
> close menu icon portait 

- src/modules/menu/components/mainMenu/MainMenu.js
- test/modules/menu/components/mainMenu/MainMenu.test.js
> add slider value 

- src/modules/map/components/olMap/OlMap.js
- test/modules/map/components/olMap/OlMap.test.js
by adding attribute "tabindex" on map container
> enable missing keyboard interaction

- src/services/provider/mapDefinitions.provider.js
- test/service/provider/mapDefinitions.provider.test.js
> adjust BVV min/max zoom levels

- src/services/ImportVectorDataService.js
- test/service/ImportVectorDataService.test.js
Derive final source type from loaded data. They might not be what they pretend to be...
Test URL: https://www.bergfex.de/downloads/gps/?type=&id=82563&fileType=kml
> take real data as input for source type detection

- src/modules/featureInfo/components/featureInfoPanel.css
> add featureinfo style

- src/modules/search/i18n/search.provider.js
- src/modules/toolbox/i18n/toolbox.provider.js
- test/modules/search/i18n/search.provider.test.js
- test/modules/toolbox/i18n/toolbox.provider.test.js
- Remove text 'WMS' in import tool.
- Change text 'Flurstück' to 'Fllustücke'.
> Enhancement text

- src/modules/toolbox/components/measureToolContent/measureToolContent.css
- src/services/provider/units.provider.js
- test/service/provider/units.provider.test.js
> MeasureToolContent: update styling&formatting

- test/modules/dndImport/components/DndImportPanel.test.js
- test/modules/geoResourceInfo/components/GeoResourceInfoPanel.test.js
- test/modules/iconSelect/components/IconSelect.test.js
- test/modules/map/components/contextMenu/MapContextMenuContent.test.js
- test/modules/map/components/olMap/OlMap.test.js
- test/modules/map/components/olMap/handler/draw/OlDrawHandler.test.js
- test/modules/map/components/olMap/handler/featureInfo/OlFeatureInfoHandler.test.js
- test/modules/map/components/olMap/handler/measure/OlMeasurementHandler.test.js
- test/modules/map/components/olMap/services/VectorLayerService.test.js
- test/modules/notifications/components/NotificationPanel.test.js
- test/modules/search/components/menu/types/cp/CpResultsPanel.test.js
- test/modules/search/components/menu/types/geoResource/GeoResourceResultsPanel.test.js
- test/modules/search/components/menu/types/location/LocationResultsPanel.test.js
- test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js
- test/modules/toolbox/components/importToolContent/ImportToolContent.test.js
- test/modules/toolbox/components/measureToolContent/MeasureToolContent.test.js
- test/modules/toolbox/components/shareButton/ShareButton.test.js
- test/modules/toolbox/components/shareButton/ShareDialogContent.test.js
- test/modules/toolbox/components/shareToolContent/ShareToolContent.test.js
- test/modules/toolbox/components/shareToolContent/ShareToolDialog.test.js
- test/modules/topics/components/menu/catalog/CatalogContentPanel.test.js
- test/plugins/DrawPlugin.test.js
- test/plugins/FeatureInfoPlugin.test.js
- test/plugins/GeolocationPlugin.test.js
- test/plugins/ImportPlugin.test.js
- test/plugins/MeasurementPlugin.test.js
- test/plugins/PositionPlugin.test.js
- test/service/ImportVectorDataService.test.js
- test/service/StoreService.test.js
- test/test-utils.js
prepare test code for karma-jasmine >= 5.0.0.
> replace usage of done() in all tests

- src/modules/map/components/olMap/handler/draw/OlDrawHandler.js
> fix _setSelection when select is deactivated

- src/modules/search/components/menu/SearchResultsPanel.js
- src/modules/search/components/menu/index.js
- src/modules/search/components/menu/types/geoResource/GeoResourceResultsPanel.js
- src/modules/topics/services/provider/catalog.provider.js
- src/services/GeoResourceService.js
- src/services/domain/geoResources.js
- src/services/provider/geoResource.provider.js
- test/modules/baseLayer/components/BaseLayerSwitcher.test.js
- test/modules/map/components/olMap/OlMap.test.js
- test/modules/search/components/menu/SearchResultsPanel.test.js
- test/modules/search/components/menu/types/geoResource/GeoResourceResultsPanel.test.js
- test/modules/search/services/SearchResultService.test.js
- test/service/ImportVectorDataService.test.js
> Fix GeoResource related typos

- src/services/provider/units.provider.js
- test/service/UnitsService.test.js
- test/service/provider/units.provider.test.js
> fix tests for units.provider

- src/services/IconService.js
- src/services/provider/icons.provider.js
- test/service/IconService.test.js
- test/service/provider/icons.provider.test.js
> fix matcher for cases of invalid idOrUrl

- src/modules/map/components/olMap/services/VectorLayerService.js
- src/modules/map/components/olMap/utils/feature.provider.js
- test/modules/map/components/olMap/services/VectorLayerService.test.js
- test/modules/map/components/olMap/util/feature.provider.test.js
> filter out features containing no geometry

- src/main.css
- src/modules/menu/components/mainMenu/content/abstractContentPanel.css
fixes #856
- Scaled the UI up for smaller devices.
- Scaled the UI down  for bigger devices
> change fontsize

- src/modules/help/components/FirstSteps.js
- test/modules/help/components/FirstSteps.test.js
adds fullscreen possibility to iframe.
> add: allowfullscreen

- src/modules/olMap/formats/kml.js
- src/modules/olMap/handler/draw/OlDrawHandler.js
- src/modules/olMap/services/StyleService.js
- src/modules/olMap/utils/olStyleUtils.js
- src/modules/toolbox/components/drawToolContent/DrawToolContent.js
- src/utils/assets.js
- src/utils/colors.js
- test/modules/olMap/util/olStyleUtils.test.js
- test/utils/assets.test.js
- test/utils/colors.test.js
> extract utils for colors & assets

- src/modules/commons/components/spinner/Spinner.js
- src/modules/utils/components/showCase/ShowCase.js
- test/modules/commons/components/Spinner.test.js
adds a label-property to spinner
fixes #1024
> Spinner with custom label

- package-lock.json
- package.json
according to https://github.com/standard/standard/issues/1316
> remove eslint-plugin-standard dependency

- src/modules/olMap/components/OlMap.js
- src/store/position/position.action.js
- src/store/position/position.reducer.js
- test/modules/map/components/zoomButtons/ZoomToExtentButton.test.js
- test/modules/olMap/components/OlMap.test.js
- test/store/position/position.reducer.test.js
Add the possibility to fit on a specific vector layer on the map
A fit request is resolved by the map implementation.
Fit requests for other layer types may be implemented in the future.
> fit to layer extent

- src/services/provider/sanitizeHtml.provider.js
- test/service/provider/sanitizeHtml.provider.test.js
update sanitizeHtmlProvider with additional blacklist of forbidden/ unsafe HTML-Tags and
filtering of SVG- and mathML-Tags
> update sanitizer with blacklist & html profile

- src/services/provider/sanitizeHtml.provider.js
- test/service/provider/sanitizeHtml.provider.test.js
coercing by additional blacklist of forbidden/ unsafe HTML-Tags and
filtering of SVG- and mathML-Tags
> coerce sanitizeHtmlProvider by additional options

- src/modules/commons/components/autocomplete/AutocompleteSearch.js
- src/modules/search/components/menu/types/cp/CpResultItem.js
- src/modules/search/components/menu/types/geoResource/GeoResourceResultItem.js
- src/modules/search/components/menu/types/location/LocationResultItem.js
- src/modules/search/services/SearchResultService.js
- src/modules/search/services/domain/searchResult.js
- src/modules/search/services/provider/searchResult.provider.js
- test/modules/commons/components/AutocompleteSearch.test.js
- test/modules/search/components/menu/types/cp/CpResultItem.test.js
- test/modules/search/components/menu/types/cp/CpResultsPanel.test.js
- test/modules/search/components/menu/types/geoResource/GeoResourceResultItem.test.js
- test/modules/search/components/menu/types/geoResource/GeoResourceResultsPanel.test.js
- test/modules/search/components/menu/types/location/LocationResultItem.test.js
- test/modules/search/components/menu/types/location/LocationResultsPanel.test.js
- test/modules/search/services/SearchResultService.test.js
- test/modules/search/services/domain/searchResult.test.js
- test/modules/search/services/provider/searchResult.provider.test.js
> refactor search result class

- src/modules/olMap/ol/source/LimitedImageWMS.js
- src/modules/olMap/services/LayerService.js
- test/modules/olMap/ol/source/LimitedImageWMS.test.js
- test/modules/olMap/services/LayerService.test.js
> visualize max size of limited image sources

- src/services/FeatureInfoService.js
- src/services/domain/geoResources.js
- src/services/provider/geoResource.provider.js
- src/services/provider/wmsCapabilities.provider.js
- test/service/FeatureInfoService.test.js
- test/service/domain/geoResources.test.js
- test/service/provider/geoResource.provider.test.js
- test/service/provider/wmsCapabilities.provider.test.js
...and handle it for user imported WMS
> extend GeoResource by property "queryable"

- src/utils/markup.js
- test/utils/markup.test.js
> add attribute based DOM traversing

- src/index.html
- src/modules/help/components/FirstSteps.js
- test/e2e/page.spec.js
Needed for 4.0, we will reuse it later.
> disable first steps hint

- src/modules/utils/components/devInfo/DevInfo.js
- test/modules/utils/components/devInfo/DevInfo.test.js
> open the showcase by clicking on the build info

- src/modules/olMap/components/OlMap.js
- test/modules/olMap/components/OlMap.test.js
Partly resolves #1090. Making it configurable for the user will be done later...
> disable intermediary zoom levels

- src/services/ImportVectorDataService.js
- src/services/ImportWmsService.js
- src/services/ShareService.js
- src/services/SourceTypeService.js
- src/services/UrlService.js
- src/services/provider/proxifyUrl.provider.js
- src/services/provider/qrCodeUrlProvider.js
- src/services/provider/urlShorteningProvider.js
- test/service/UrlService.test.js
- test/service/provider/qrCodeUrl.provider.test.js
fixes #1155  (also some cleanup and typo fixes)
> fix call of  BVV URL shortener service

- .github/workflows/node.js.yml
- package-lock.json
add `npm audit` (https://docs.npmjs.com/cli/v8/commands/npm-audit) to  our CI pipeline
> run "npm audit"

- src/modules/olMap/services/InteractionStorageService.js
- test/modules/olMap/services/InteractionStorageService.test.js
> fix i18n key  for InteractionStorageService

- src/services/MfpService.js
- test/service/MfpService.test.js
Changes:
- MfpService: #getCapabiliiesById -> #getLayoutById
- Data model
> add property 'grSubstitutions'

- src/modules/commons/components/button/Button.js
- src/modules/commons/components/button/button.css
- src/modules/utils/components/showCase/ShowCase.js
- test/modules/commons/components/Button.test.js
> add: button loading 

- README.md
- package-lock.json
- package.json
- src/main.js
- src/modules/profile/components/Profile.js
- src/modules/profile/components/profile.css
- src/modules/profile/index.js
- src/modules/utils/components/showCase/ShowCase.js
- test/modules/profile/components/Profile.test.js
Chart.js integration as a starting point for profile development
> integrate Chart.js

- package-lock.json
- package.json
This reverts commit 2d7459b2b0fcdd0c4a1636c40f258262bac971a3.
> Revert "build(deps-dev): bump karma-webkit-launcher from 1.0.2 to 1.1.0"

- .stylelintrc
- package.json
- src/modules/commons/components/button/button.css
- src/modules/commons/components/overflowMenu/menuitem.css
- src/modules/commons/components/overflowMenu/overflowmenu.css
- src/modules/featureInfo/components/featureInfoPanel.css
- src/modules/header/components/header.css
- src/modules/map/components/contextMenu/mapContextMenu.css
- src/modules/map/components/geolocationButton/geolocationButton.css
- src/modules/profile/components/profile.css
- src/modules/search/components/menu/types/cp/cpResultItem.css
- src/modules/search/components/menu/types/geoResource/geoResourceResultsPanel.css
- src/modules/search/components/menu/types/location/locationResultItem.css
- src/modules/toolbox/components/drawToolContent/drawToolContent.css
- src/modules/toolbox/components/importToolContent/importToolContent.css
- src/modules/toolbox/components/toolBar/toolBar.css
- src/modules/toolbox/components/toolContainer/abstractToolContent.css
- src/modules/toolbox/components/toolContainer/toolContainer.css
- src/modules/topics/components/menu/topicsContentPanel.css
- not auto-fixable errors should be reported (again).
- apply updated rules
> re-configure stylelint

- src/modules/olMap/services/Mfp3Encoder.js
> remove url-encoding of text style content

- src/plugins/ExportMfpPlugin.js
- test/plugins/ExportMfpPlugin.test.js
> restore map rotation after quitting export tool

- src/services/MfpService.js
- src/services/provider/mfp.provider.js
- test/plugins/ExportMfpPlugin.test.js
- test/service/MfpService.test.js
- test/service/mfp.provider.test.js
> fix mfp related typos

- src/modules/olMap/handler/mfp/OlMfpHandler.js
- test/modules/olMap/handler/mfp/OlMfpHandler.test.js
> fix OlMfpHandler calculation of optimalScale

- src/modules/olMap/services/Mfp3Encoder.js
- test/modules/olMap/formats/Mfp3Encoder.test.js
> filter invisible Layers

- src/modules/olMap/services/Mfp3Encoder.js
- test/modules/olMap/formats/Mfp3Encoder.test.js
> Fix empty data owner

- src/modules/olMap/services/Mfp3Encoder.js
> remove warning for missing GeoResource

- .github/workflows/node.js.yml
> run npm audit only for prod dependencies

- src/services/IconService.js
- src/services/provider/icons.provider.js
- test/service/IconService.test.js
- test/service/provider/icons.provider.test.js
update building of icons-url
fixes #1263
> add extension name to icons-url

- src/modules/olMap/services/Mfp3Encoder.js
- test/modules/olMap/formats/Mfp3Encoder.test.js
> Export2Pdf: add missing MultiPolygon handling

- src/modules/olMap/services/Mfp3Encoder.js
- test/modules/olMap/formats/Mfp3Encoder.test.js
fix behavior on empty layer specs
> Export2Pdf: prevent empty layer specs

- src/modules/olMap/services/Mfp3Encoder.js
- test/modules/olMap/formats/Mfp3Encoder.test.js
> Export2Pdf: fix encoding of dataOwner 

- test/plugins/ExportMfpPlugin.test.js
> remove unneeded await for timeout

- src/modules/search/components/menu/types/geoResource/GeoResourceResultItem.js
- test/modules/search/components/menu/types/geoResource/GeoResourceResultItem.test.js
> remove alwaysOnTop constraint for preview layer

- .eslintrc.js
- README.md
- package.json
> bumb JS version to ECMAScript 2021 (ES12)

- src/modules/olMap/services/Mfp3Encoder.js
- test/modules/olMap/formats/Mfp3Encoder.test.js
fix encoding of measurement geometries consisting of only two coordinates
> fix encoding of measurement geometries

- src/modules/olMap/services/Mfp3Encoder.js
- src/modules/olMap/utils/olStyleUtils.js
- test/modules/olMap/formats/Mfp3Encoder.test.js
- test/modules/olMap/util/olStyleUtils.test.js
- add fill style for measurement features (fallback-style)
- update label-style for encoded overlays
> Export2Pdf: update style for measurement

- src/modules/olMap/handler/featureInfo/featureInfoItem.provider.js
- src/plugins/FeatureInfoPlugin.js
- test/modules/olMap/handler/featureInfo/featureInfoItem.provider.test.js
- test/plugins/FeatureInfoPlugin.test.js
> fix broken feature info title

- src/modules/search/components/menu/types/geoResource/GeoResourceResultItem.js
- src/modules/search/components/menu/types/geoResource/geoResourceResultItem.css
- test/modules/search/components/menu/types/geoResource/GeoResourceResultItem.test.js
> add: loading style

- src/modules/olMap/utils/olStyleUtils.js
- test/modules/olMap/util/olStyleUtils.test.js
> add defaultStyle for GeometryCollections

- src/store/altitudeProfile/altitudeProfile.action.js
- src/utils/checks.js
- test/test-utils.js
Usage:
```
const renderedElement = TestUtils.renderTemplateResult(html`<style>foo}</style><iframe title='title' src='src' allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true"></iframe>`);
expect(renderedElement.querySelector('iframe').getAttribute('allowfullscreen')).toBe('true');
expect(renderedElement.querySelector('iframe').getAttribute('title')).toBe('title');
```
> add test-util for direct rendering of TemplateResult

- src/modules/olMap/services/Mfp3Encoder.js
- test/modules/olMap/formats/Mfp3Encoder.test.js
> Export2Pdf: fix qr-code encoding

- src/injection/config.js
- src/modules/utils/components/showCase/ShowCase.js
- src/plugins/AltitudeProfilePlugin.js
- src/services/AltitudeService.js
- src/services/StoreService.js
- src/services/provider/profile.provider.js
- src/utils/storeUtils.js
- test/plugins/AltitudeProfilePlugin.test.js
- test/service/AltitudeService.test.js
- test/service/StoreService.test.js
- test/service/provider/profile.provider.test.js
> AltitudeProfile: add infrastructure

- src/modules/commons/components/toggle/Toggle.js
- test/modules/commons/components/Toggle.test.js
> Toggle component does not work in Chrome

- src/modules/olMap/services/VectorLayerService.js
- test/modules/olMap/services/VectorLayerService.test.js
> fix overlay visibility

- src/modules/olMap/handler/mfp/OlMfpHandler.js
- src/modules/olMap/handler/mfp/styleUtils.js
- test/modules/olMap/handler/mfp/OlMfpHandler.test.js
- test/modules/olMap/handler/mfp/styleUtils.test.js
> Export2Pdf: fix flickering preview mask

- src/modules/header/i18n/header.provider.js
- test/modules/header/i18n/header.provider.test.js
> adjust header badge label

- src/modules/olMap/handler/mfp/OlMfpHandler.js
- test/modules/olMap/handler/mfp/OlMfpHandler.test.js
> reset mfpBoundary on deactivate

- src/modules/olMap/services/Mfp3Encoder.js
- test/modules/olMap/formats/Mfp3Encoder.test.js
> Export2Pdf: fix attributions

- src/plugins/ExportMfpPlugin.js
- test/plugins/ExportMfpPlugin.test.js
This reverts commit 3753a99049f2f0ded8283687a550aafc5651f1c3.
> Revert "open PDF in new tab"

- src/modules/elevationProfile/components/ElevationProfile.js
- test/modules/elevationProfile/components/ElevationProfile.test.js
> ElevationProfile: when disconnected destroys chart

- src/modules/elevationProfile/components/ElevationProfile.js
>  ElevationProfile: remove unneeded axis label

- src/modules/elevationProfile/components/ElevationProfile.js
- test/modules/elevationProfile/components/ElevationProfile.test.js
> ElevationProfile: configure default text color 

- test/modules/chips/components/ChipsContainer.test.js
> ChipsContainer: fix flaky test

- src/modules/olMap/services/Mfp3Encoder.js
- test/modules/olMap/formats/Mfp3Encoder.test.js
> Export2Pdf: add support for GeoResource.VT

- src/modules/elevationProfile/components/ElevationProfile.js
- test/modules/elevationProfile/components/ElevationProfile.test.js
> ElevationProfile: missing test for #onDisconnect restored

- src/modules/elevationProfile/components/ElevationProfile.js
- test/modules/elevationProfile/components/ElevationProfile.test.js
> ElevationProfile: remove highlight feature when component disconnects

- src/modules/elevationProfile/components/ElevationProfile.js
- test/modules/elevationProfile/components/ElevationProfile.test.js
> ElevationProfile: enable and slow down animation

- src/modules/elevationProfile/components/ElevationProfile.js
- test/modules/elevationProfile/components/ElevationProfile.test.js
> ElevationProfile: display empty profile when no coordinates are available

- src/services/ElevationService.js
- test/service/ElevationService.test.js
Elevation profile shows mocked data now when app is in standalone mode.
> ElevationService: return mocked data in standalone mode

- src/modules/elevationProfile/components/ElevationProfile.js
- test/modules/elevationProfile/components/ElevationProfile.test.js
> ElevationProfile: profile does not always update properly 

- src/plugins/ElevationProfilePlugin.js
- src/store/elevationProfile/elevationProfile.action.js
- src/store/elevationProfile/elevationProfile.reducer.js
- test/plugins/ElevationProfilePlugin.test.js
- test/store/evelationProfile/elevationProfile.reducer.test.js
According to v3, the profile should be closed when the draw or measurement tool is deactivated.
> finetune elevation profile behavior

- src/modules/olMap/formats/kml.js
- src/modules/olMap/handler/measure/OlMeasurementHandler.js
- src/modules/toolbox/components/measureToolContent/MeasureToolContent.js
- test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
- test/modules/toolbox/components/measureToolContent/MeasureToolContent.test.js
> OlMeasurementHandler: Wait with saving until features are loaded

- src/modules/elevationProfile/components/ElevationProfile.js
- test/modules/elevationProfile/components/ElevationProfile.test.js
> ElevationProfile: optimize scale of y-axis

- src/modules/elevationProfile/components/ElevationProfile.js
- src/modules/elevationProfile/i18n/elevationProfile.provider.js
- test/modules/elevationProfile/components/ElevationProfile.test.js
- test/modules/elevationProfile/i18n/elevationProfile.provider.test.js
> ElevationProfile now emits error notification

- src/services/ProcessEnvConfigService.js
- src/services/TranslationService.js
- src/services/provider/units.provider.js
- src/utils/numberUtils.js
- test/service/ProcessEnvConfigService.test.js
- test/service/UnitsService.test.js
- test/service/provider/units.provider.test.js
- test/utils/numberUtils.test.js
Formates a number accordingly to the current `DEFAULT_LANG` property
> add number-to-locale-string function

- src/modules/elevationProfile/components/ElevationProfile.js
- src/utils/colors.js
- test/modules/elevationProfile/components/ElevationProfile.test.js
- test/utils/colors.test.js
Using colors by slope-class based on a classification of [Soter-Model]( https://esdac.jrc.ec.europa.eu/projects/SOTER/Soter_Model.html)
> ElevationProfile: use color classes for slope values

- src/modules/elevationProfile/components/ElevationProfile.js
- test/modules/elevationProfile/components/ElevationProfile.test.js
> ElevationProfile: use UnitsService for distances

- src/modules/olMap/handler/elevationProfile/ElevationProfileHandler.js
- test/modules/olMap/handler/elevationProfile/ElevationProfileHandler.test.js
> ElevationProfile: update coordinates on close

- src/modules/olMap/handler/mfp/OlMfpHandler.js
- src/modules/olMap/i18n/olMap.provider.js
- src/modules/olMap/services/Mfp3Encoder.js
- test/modules/olMap/formats/Mfp3Encoder.test.js
- test/modules/olMap/handler/mfp/OlMfpHandler.test.js
- test/modules/olMap/i18n/olMap.provider.test.js
> Export2Pdf: Mfp3Encoder filters unsupported layer

- src/modules/iframe/components/iframeGenerator/IframeGenerator.js
> use textarea value-Property

- README.md
- src/services/ProcessEnvConfigService.js
- src/services/ShareService.js
- test/service/ProcessEnvConfigService.test.js
- test/service/ShareService.test.js
by introducing the new config parameter `FRONTEND_URL`.
> ShareService: fix encodeState()

- src/modules/olMap/handler/elevationProfile/OlElevationProfileHandler.js
- src/modules/olMap/handler/featureInfo/featureInfoItem.provider.js
- src/modules/olMap/utils/olGeometryUtils.js
- test/modules/olMap/util/olGeometryUtils.test.js
> ElevationProfile: simplify profile geometries

- src/plugins/ElevationProfilePlugin.js
- test/plugins/ElevationProfilePlugin.test.js
> ElevationProfilePlugin: ensure unsubscription of bottomSheet observer

- src/modules/olMap/handler/elevationProfile/OlElevationProfileHandler.js
- src/store/elevationProfile/elevationProfile.action.js
- src/store/elevationProfile/elevationProfile.reducer.js
- test/plugins/ElevationProfilePlugin.test.js
- test/store/evelationProfile/elevationProfile.reducer.test.js
Remove possible side effect when closing the profile.
> optimize elevationProfile slice-of-state

- src/modules/olMap/utils/olGeometryUtils.js
- test/modules/olMap/util/olGeometryUtils.test.js
> FeatureInfoItem: add support for MultiLineString

- src/modules/iframe/components/activateMapButton/ActivateMapButton.js
- test/modules/iframe/components/ActivateMapButton.test.js
- test/modules/iframe/components/DrawTool.test.js
Do not show component when `T_DISABLE_INITIAL_UI_HINTS=true`
> ActivateMapButton: check query parameter

- src/modules/utils/components/showCase/ShowCase.js
Background: `input` elements must be self-closing otherwise Prettier won't format template strings
> fix Showcase formatting

- src/main.css
- src/modules/baElement.css
- src/modules/chips/components/chipsContainer/chipsContainer.css
- src/modules/commons/components/button/button.css
- src/modules/footer/components/footer.css
- src/modules/header/components/header.css
- src/modules/help/components/firststeps.css
- src/modules/iframe/components/activateMapButton/activateMapButton.css
- src/modules/iframe/components/tools/drawTool.css
- src/modules/menu/components/mainMenu/content/abstractContentPanel.css
- src/modules/menu/components/mainMenu/mainMenu.css
- src/modules/modal/components/modal.css
- src/modules/search/components/menu/types/cp/cpResultsPanel.css
- src/modules/search/components/menu/types/geoResource/geoResourceResultsPanel.css
- src/modules/search/components/menu/types/location/locationResultsPanel.css
- src/modules/stackables/components/bottomSheet.css
- src/modules/toolbox/components/drawToolContent/drawToolContent.css
- src/modules/toolbox/components/importToolContent/importToolContent.css
- src/modules/toolbox/components/measureToolContent/measureToolContent.css
- src/modules/toolbox/components/shareToolContent/shareToolContent.css
> fix css typo

- src/modules/iframe/components/generator/IframeGenerator.js
- test/modules/iframe/components/IframeGenerator.test.js
> IframeGenerator: update Min/Max-Values and render-behavior

- src/modules/menu/components/mainMenu/content/misc/BvvMiscContentPanel.js
- src/modules/menu/components/mainMenu/content/misc/assets/feedback.svg
- src/modules/menu/components/mainMenu/content/misc/bvvMiscContentPanel.css
- src/modules/menu/i18n/menu.provider.js
- test/modules/menu/components/mainMenu/content/more/BvvMiscContentPanel.test.js
- test/modules/menu/i18n/menu.provider.test.js
> ToggleFeedbackPanel: add to menu (open Dialog)

- src/modules/feedback/components/mapFeedback/MapFeedbackPanel.js
- test/modules/feedback/components/mapFeedback/MapFeedbackPanel.test.js
> MapFeedback:security

- src/plugins/MainMenuPlugin.js
- src/store/mainMenu/mainMenu.action.js
- test/plugins/MainMenuPlugin.test.js
The "maps" tab is now the default tab.
> adjust default tab-id

- src/plugins/IframeGeometryIdPlugin.js
- test/plugins/IframeGeometryIdPlugin.test.js
> IFrameGeometryIdPlugIn:  add null-check

- src/modules/olMap/handler/draw/OlDrawHandler.js
- src/modules/olMap/handler/measure/OlMeasurementHandler.js
- test/modules/olMap/handler/draw/OlDrawHandler.test.js
- test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
> OlDrawHandler: prevent invalid fileSaveResult payload

- src/modules/feedback/components/generalFeedback/GeneralFeedbackPanel.js
- src/modules/feedback/components/mapFeedback/MapFeedbackPanel.js
- test/modules/feedback/components/generalFeedback/GeneralFeedbackPanel.test.js
- test/modules/feedback/components/mapFeedback/MapFeedbackPanel.test.js
- test/modules/search/components/menu/types/geoResource/GeoResourceResultItem.test.js
> GeneralFeedback fix wrong i18n key

- test/modules/chips/components/AbstractAssistChip.test.js
> AbstractAssistChip TestCase: prevent unnecessary browser warnings

- src/modules/feedback/components/generalFeedback/GeneralFeedbackPanel.js
- test/modules/feedback/components/generalFeedback/GeneralFeedbackPanel.test.js
> GeneralFeedback included category

- src/domain/mediaTypes.js
- src/modules/dndImport/components/DndImportPanel.js
- src/modules/export/components/dialog/ExportDialogContent.js
- src/modules/export/components/dialog/ExportItem.js
- src/modules/geoResourceInfo/services/provider/geoResourceInfoResult.provider.js
- src/services/FileSaveService.js
- src/services/HttpService.js
- src/services/provider/featureInfo.provider.js
- src/services/provider/feedback.provider.js
- src/services/provider/mfp.provider.js
- src/services/provider/profile.provider.js
- src/services/provider/sourceType.provider.js
- src/services/provider/wmsCapabilities.provider.js
- test/domain/mediaTypes.test.js
- test/modules/dndImport/components/DndImportPanel.test.js
- test/modules/export/components/dialog/ExportDialogContent.test.js
- test/modules/geoResourceInfo/services/provider/geoResourceInfoResult.provider.test.js
- test/modules/toolbox/components/importToolContent/ImportToolContent.test.js
- test/plugins/ImportPlugin.test.js
- test/service/FileSaveService.test.js
- test/service/HttpService.test.js
- test/service/ImportVectorDataService.test.js
- test/service/mfp.provider.test.js
- test/service/provider/featureInfo.provider.test.js
- test/service/provider/feedback.provider.test.js
- test/service/provider/profile.provider.test.js
- test/service/provider/sourceType.provider.test.js
- test/service/provider/wmsCapabilities.provider.test.js
> move mediaType enum

- src/services/ExportVectorDataService.js
- test/service/ExportVectorDataService.test.js
> ExportVectorDataService: add handling for unexpected SourceTypeResultStatus

- src/modules/olMap/services/StyleService.js
- src/modules/olMap/utils/olStyleUtils.js
- test/modules/olMap/services/StyleService.test.js
> StyleService: fix style mapping

- src/domain/geoResources.js
- src/services/provider/geoResource.provider.js
- test/domain/geoResources.test.js
- test/service/provider/geoResource.provider.test.js
> add missing label for GeoResouceFuture

- src/modules/iframe/components/generator/iframegenerator.css
> fix: #1729

- src/modules/geoResourceInfo/services/GeoResourceInfoService.js
- src/modules/topics/services/CatalogService.js
- src/services/AdministrationService.js
- src/services/ElevationService.js
- src/services/MfpService.js
- src/services/provider/fileStorage.provider.js
- test/modules/geoResourceInfo/services/GeoResourceInfoService.test.js
- test/modules/topics/services/CatalogService.test.js
- test/service/AdministrationService.test.js
- test/service/ElevationService.test.js
- test/service/MfpService.test.js
- test/service/provider/fileStorage.provider.test.js
> ES2022: adopting error.cause

- src/modules/feedback/components/rating/likertItemRatingPanel.css
- src/modules/feedback/components/toggleFeedback/ToggleFeedbackPanel.js
- src/modules/feedback/components/toggleFeedback/toggleFeedbackPanel.css
- test/modules/feedback/components/toggleFeedback/ToggleFeedbackPanel.test.js
Add properties `type` and `center`:
```
const content = html`<ba-mvu-togglefeedbackpanel .onSubmit=${closeModal} .type=${FeedbackType.MAP} center=${mapCenter}></ba-mvu-togglefeedbackpanel>`;
openModal(title, content);
```
> extend ToggleFeedbackPanel

- src/modules/map/components/assistChips/MapFeedbackChip.js
- src/modules/map/components/assistChips/assets/map.svg
- src/modules/map/components/assistChips/index.js
- src/modules/map/components/contextMenu/MapContextMenuContent.js
- src/modules/map/i18n/assistChips.provider.js
- test/modules/map/components/assistChips/MapFeedbackChip.test.js
- test/modules/map/components/contextMenu/MapContextMenuContent.test.js
- test/modules/map/i18n/assistChips.provider.test.js
> MapFeedbackChip

- src/modules/help/components/FirstSteps.js
- src/modules/iframe/components/activateMapButton/ActivateMapButton.js
- src/modules/iframe/components/chips/ViewLargerMapChip.js
- src/modules/iframe/components/tools/DrawTool.js
- src/plugins/ChipsPlugin.js
- src/plugins/HighlightPlugin.js
- src/plugins/LayersPlugin.js
- src/plugins/MainMenuPlugin.js
- src/plugins/PositionPlugin.js
- src/plugins/SearchPlugin.js
- src/plugins/ToolsPlugin.js
- src/plugins/TopicsPlugin.js
- src/services/EnvironmentService.js
- test/modules/export/components/dialog/ExportDialogContent.test.js
- test/modules/help/components/FirstSteps.test.js
- test/modules/iframe/components/ActivateMapButton.test.js
- test/modules/iframe/components/DrawTool.test.js
- test/modules/iframe/components/ViewLargerMapChip.test.js
- test/plugins/ChipsPlugin.test.js
- test/plugins/HighlightPlugin.test.js
- test/plugins/LayersPlugin.test.js
- test/plugins/MainMenuPlugin.test.js
- test/plugins/PositionPlugin.test.js
- test/plugins/SearchPlugin.test.js
- test/plugins/ToolsPlugin.test.js
- test/plugins/TopicsPlugin.test.js
- test/service/EnvironmentService.test.js
> rename getUrlParams to getQueryParams

- src/modules/topics/services/CatalogService.js
- src/modules/topics/services/provider/catalog.provider.js
- src/services/TopicsService.js
- src/services/provider/topics.provider.js
- test/modules/topics/components/menu/catalog/CatalogContentPanel.test.js
- test/modules/topics/components/menu/catalog/CatalogNode.test.js
- test/modules/topics/services/CatalogService.test.js
- test/modules/topics/services/provider/catalog.provider.test.js
> improve docs for TopicService and CatalogService

- src/modules/feedback/components/toggleFeedback/ToggleFeedbackPanel.js
- src/modules/menu/components/mainMenu/content/misc/BvvMiscContentPanel.js
- src/modules/modal/components/Modal.js
- src/store/modal/modal.action.js
- src/store/modal/modal.reducer.js
- test/modules/feedback/components/toggleFeedback/ToggleFeedbackPanel.test.js
- test/modules/menu/components/mainMenu/content/more/BvvMiscContentPanel.test.js
- test/modules/modal/components/Modal.test.js
- test/store/modal/modal.reducer.test.js
For a real-life example have a look at the feedback dialog.
> Modal: multiple-dialog usage

- src/modules/map/components/contextMenu/MapContextMenu.js
- src/modules/modal/components/Modal.js
- test/modules/map/components/contextMenu/MapContextMenu.test.js
- test/modules/modal/components/Modal.test.js
Close context menu when ESC key is pressed
> MapContextMenu: add ESC key listener

- src/modules/stackables/components/bottomSheet/bottomSheet.css
> remove min-width to avoid overlap

- test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
fix flaky tests, related to async store operations
> OlMeasurementHandler:fix flaky tests

- src/services/IconService.js
- src/services/provider/iconColor.provider.js
- src/services/provider/iconUrl.provider.js
- src/services/provider/icons.provider.js
- test/service/IconService.test.js
- test/service/provider/iconUrl.provider.test.js
> IconUrl.provider

- .github/workflows/node.js.yml
Run pipeline also when a PR is opened from a fork.
> trigger pipeline on pull_request

- src/plugins/LayersPlugin.js
- src/services/ShareService.js
- test/service/ShareService.test.js
> fix ShareService

- src/modules/olMap/handler/measure/OlMeasurementHandler.js
Resolves #1877
proposed fix:
unsubscribe and clear drawing listeners
> always clear drawing listeners on deactivate

- src/modules/elevationProfile/components/panel/ElevationProfile.js
- test/modules/elevationProfile/components/panel/ElevationProfile.test.js
> ElevationProfile: fixed Safari Problem

- src/services/provider/mfp.provider.js
- test/service/mfp.provider.test.js
> mfp provider: adjust timeout

- src/modules/olMap/handler/draw/OlDrawHandler.js
- test/modules/olMap/handler/draw/OlDrawHandler.test.js
> OlDrawHandler:  fix text-property on re-select of drawing-feature

- src/domain/geoResources.js
- src/modules/feedback/components/mapFeedback/MapFeedbackPanel.js
- src/services/provider/geoResource.provider.js
- src/utils/checks.js
- test/modules/feedback/components/mapFeedback/MapFeedbackPanel.test.js
- test/utils/checks.test.js
Ticket#4598103 
(see also #1904 )
> MapFeedbackPanel: filter external GeoResources

- src/modules/layerManager/components/LayerItem.js
- test/modules/layerManager/components/LayerItem.test.js
> LayerItem: open modal with current label

- src/services/ImportVectorDataService.js
- src/services/provider/sourceType.provider.js
- test/service/ImportVectorDataService.test.js
- test/service/provider/sourceType.provider.test.js
> fix import of vector data from URL

- src/plugins/IframeStatePlugin.js
- test/plugins/IframeStatePlugin.test.js
> IframeStatePlugin: avoid error when parent has not the same origin

- src/modules/map/components/contextMenu/MapContextMenu.js
> MapContextMenu: adjust map context menu border

- src/services/provider/sanitizeHtml.provider.js
- test/service/provider/sanitizeHtml.provider.test.js
> adjust DomPurify

- src/modules/featureInfo/components/featureInfoIframePanel/featureInfoIframePanel.css
- src/modules/featureInfo/components/featureInfoPanel/featureInfoPanel.css
> fix: overflow-x

- .github/workflows/node.js.yml
- README.md
- bundlesize.config.json
- package-lock.json
- package.json
- test/e2e/entryPointsAndChunks.spec.js
see https://github.com/siddharthkp/bundlesize
> check bundle size with bundlesize

- package-lock.json
- package.json
bundlesize uses a version of `node-gyp` requiring python2
> use bundlesize2 instead of bundlesize

- src/injection/config.js
- src/plugins/BeforeUnloadPlugin.js
- src/services/StoreService.js
- test/injection/config.test.js
- test/plugins/BeforeUnloadPlugin.test.js
- test/service/StoreService.test.js
and a tool is currently active.
> inform the user when leaving the page

- src/services/ExportVectorDataService.js
- test/service/ExportVectorDataService.test.js
> fix EWKT export for multiple geometries

- src/plugins/BeforeUnloadPlugin.js
- test/plugins/BeforeUnloadPlugin.test.js
Relevant active tools are now  `[Tools.DRAW, Tools.MEASURE, Tools.MEASURE]` only
> adjust beforeUnload behavior

- src/modules/olMap/utils/olStyleUtils.js
- test/modules/olMap/util/olStyleUtils.test.js
> adjust text position on symbol (picked from #2026  )

- src/modules/routing/components/categoryBar/CategoryBar.js
- test/modules/routing/components/CategoryBar.test.js
optimize usage of categories from routingService
> Routing: refactor CategoryBar 

- src/modules/iframe/components/activateMapButton/activateMapButton.css
> relocate activation button

- src/modules/map/components/contextMenu/MapContextMenu.js
- src/plugins/ContextClickPlugin.js
- src/plugins/RoutingPlugin.js
- src/store/mapContextMenu/mapContextMenu.action.js
- src/store/mapContextMenu/mapContextMenu.reducer.js
- test/modules/map/components/contextMenu/MapContextMenu.test.js
- test/plugins/RoutingPlugin.test.js
- test/store/mapContextMenu/mapContextMenu.reducer.test.js
- the `RoutingPlugins` handles now a coordinate proposal of type `START_OR_DESTINATION`
- this PR contains also a small refactoring of the `mapContextMenu` s-o-s
> RoutingPlugin: handle coordinate proposal

- src/modules/elevationProfile/components/panel/ElevationProfile.js
- src/services/ElevationService.js
- test/modules/elevationProfile/components/panel/ElevationProfile.test.js
adds a fix for slope values of zero
> ElevationProfile: zero slope values

- src/domain/queryParameters.js
- src/plugins/LayersPlugin.js
- test/domain/queryParameters.test.js
- test/plugins/LayersPlugin.test.js
* add new parameter 'ZOOM_TO_EXTENT'
* handle query parameter ZOOM_TO_EXTENT
* fix typo
> v4.1: add QueryParameter for zooming on the extent of a layer (#2092)

- package-lock.json
- package.json
- src/modules/baseLayer/components/container/BaseLayerContainer.js
- src/modules/commons/components/button/Button.js
- src/modules/feedback/components/toggleFeedback/ToggleFeedbackPanel.js
- src/modules/header/components/Header.js
- src/modules/iframe/components/generator/IframeGenerator.js
- src/modules/layerManager/components/LayerManager.js
- src/modules/map/components/attributionInfo/AttributionInfo.js
- src/modules/olMap/components/OlMap.js
- src/modules/olMap/handler/mfp/OlMfpHandler.js
- src/modules/olMap/services/Mfp3Encoder.js
- src/modules/olMap/services/VectorLayerService.js
- src/modules/share/components/dialog/ShareDialogContent.js
- src/services/GeoResourceService.js
- src/services/provider/wmsCapabilities.provider.js
- test/service/TranslationService.test.js
- test/test-utils.js
Let's avoid code confusion between the `master` and `v4.1` branch
> v4.1: update prettier

- src/modules/menu/components/mainMenu/content/routing/routingPanel.css
> fix: chips are not always fully visible

- src/modules/olMap/components/OlMap.js
- src/store/position/position.action.js
- src/utils/mapUtils.js
- test/modules/olMap/components/OlMap.test.js
- test/utils/mapUtils.test.js
> avoid double WMS GetMap requests

- src/services/EnvironmentService.js
- test/service/EnvironmentService.test.js
> EnvironmentService: extend input device detection

- src/modules/olMap/services/StyleService.js
- src/modules/olMap/utils/olStyleUtils.js
- src/utils/colors.js
- test/modules/olMap/services/StyleService.test.js
- test/modules/olMap/util/olStyleUtils.test.js
- test/utils/colors.test.js
> StyleService: add type attribute detection

- src/modules/olMap/services/StyleService.js
- src/modules/olMap/utils/olStyleUtils.js
- src/utils/colors.js
- test/modules/olMap/services/StyleService.test.js
- test/modules/olMap/util/olStyleUtils.test.js
- test/utils/colors.test.js
* add style detection for feature-attribute 'type'
* update text-color for markerstyle
* update marker styles
* update calculation of contrast color
* add/update tests
> v4.1: StyleService - add type attribute detection

- src/modules/toolbox/components/toolContainer/ToolContainer.js
- src/modules/toolbox/components/toolContainer/toolContainer.css
- test/modules/toolbox/components/toolContainer/ToolContainer.test.js
> remove close button

- src/domain/routing.js
- src/modules/olMap/handler/routing/OlRoutingHandler.js
- src/modules/olMap/i18n/olMap.provider.js
- src/modules/routing/components/feedbackBanner/FeedbackBanner.js
- src/modules/routing/i18n/routing.provider.js
- src/services/RoutingService.js
- src/services/provider/route.provider.js
- test/domain/routing.test.js
- test/modules/olMap/handler/routing/OlRoutingHandler.test.js
- test/modules/olMap/i18n/olMap.provider.test.js
- test/modules/routing/components/FeedbackBanner.test.js
- test/modules/routing/i18n/routing.provider.test.js
- test/service/RoutingService.test.js
- test/service/provider/route.provider.test.js
> Routing: optimize feedback in case of error

- src/modules/stackables/components/notificationItem/notificationItem.css
> change pointer-event position

- src/modules/routing/components/routeInfo/RouteInfo.js
- test/modules/routing/components/RouteInfo.test.js
> RouteInfo:update view while stats are missing

- src/modules/stackables/components/stackableContentPanel/stackableContentPanel.css
> fix z-index

- src/modules/olMap/handler/elevationProfile/OlElevationProfileHandler.js
- src/modules/olMap/handler/routing/OlRoutingHandler.js
- src/modules/olMap/handler/selectableFeature/OlSelectableFeatureHandler.js
- src/store/routing/routing.action.js
- src/store/routing/routing.reducer.js
- test/modules/olMap/handler/elevationProfile/OlElevationProfileHandler.test.js
- test/modules/olMap/handler/routing/OlRoutingHandler.test.js
- test/store/routing/routing.reducer.test.js
resolves #2149, additionally,  fixes a problem with the `OlElevationProfileHandler`
> Routing: reset stats in case of errror

- src/modules/olMap/handler/routing/OlRoutingHandler.js
- test/modules/olMap/handler/routing/OlRoutingHandler.test.js
> Routing: prevent non unique feature ids

- src/modules/feedback/components/mapFeedback/MapFeedbackPanel.js
- src/modules/feedback/components/mapFeedback/mapFeedbackPanel.css
- test/modules/feedback/components/mapFeedback/MapFeedbackPanel.test.js
> Optimize map feedback 

- src/modules/baElement.css
- src/modules/commons/components/button/button.css
- src/modules/commons/components/icon/Icon.js
> Replace focus width focus-visible

- src/modules/commons/components/switch/switch.css
- src/modules/iframe/components/generator/iframegenerator.css
- test/modules/commons/components/Switch.test.js
> Optimize IframeGenerator component

- src/modules/olMap/handler/draw/OlDrawHandler.js
- src/store/draw/draw.action.js
- test/modules/olMap/handler/draw/OlDrawHandler.test.js
> OlDrawHandler: Fix  style change behavior

- src/modules/olMap/services/VectorLayerService.js
- src/services/UrlService.js
- test/modules/olMap/services/VectorLayerService.test.js
- test/service/UrlService.test.js
> handle v4 and legacy icon URLs

- src/modules/olMap/services/VectorLayerService.js
- src/services/UrlService.js
- test/modules/olMap/services/VectorLayerService.test.js
- test/service/UrlService.test.js
> v4.1: handle v4 and legacy icon URLs

- src/services/ExportVectorDataService.js
- test/service/ExportVectorDataService.test.js
> ExportVectorDataService: add handling for MultiPolygon in gpx

- src/modules/auth/components/BvvPlusPasswordCredentialFooter.js
- src/modules/auth/components/PasswordCredentialPanel.js
- src/modules/auth/components/bvvpluspasswordcredentialfooter.css
- src/modules/auth/components/passwordcredentialpanel.css
- src/modules/auth/i18n/passwordcredential.provider.js
- src/modules/auth/index.js
- src/modules/utils/components/showCase/ShowCase.js
- test/modules/auth/components/BvvPlusPasswordCredentialFooter.test.js
- test/modules/auth/components/PasswordCredentialPanel.test.js
- test/modules/auth/i18n/passwordcredential.provider.test.js
> PasswordCredentialPanel: add form validation and footer

- src/domain/roles.js
- src/injection/config.js
- src/modules/auth/components/BvvPlusPasswordCredentialFooter.js
- src/modules/auth/i18n/passwordcredential.provider.js
- src/modules/geoResourceInfo/services/provider/geoResourceInfoResult.provider.js
- src/modules/olMap/utils/baaImageLoadFunction.provider.js
- src/services/AuthService.js
- src/services/GeoResourceService.js
- src/services/HttpService.js
- src/services/StoreService.js
- src/services/provider/auth.provider.js
- src/services/provider/featureInfo.provider.js
- src/store/auth/auth.action.js
- src/store/auth/auth.reducer.js
- test/domain/roles.test.js
- test/modules/auth/components/BvvPlusPasswordCredentialFooter.test.js
- test/modules/auth/i18n/passwordcredential.provider.test.js
- test/modules/geoResourceInfo/services/provider/geoResourceInfoResult.provider.test.js
- test/modules/olMap/util/baaImageLoadFunction.provider.test.js
- test/service/AuthService.test.js
- test/service/GeoResourceService.test.js
- test/service/HttpService.test.js
- test/service/StoreService.test.js
- test/service/provider/auth.provider.test.js
- test/service/provider/featureInfo.provider.test.js
- test/store/auth/auth.reducer.test.js
- test/store/bottomSheet/bottomSheet.reducer.test.js
> extend authentication infrastructure

- karma.conf.gha.js
- src/domain/errors.js
- src/i18n/global.provider.js
- src/injection/config.js
- src/plugins/GlobalErrorPlugin.js
- src/services/StoreService.js
- test/domain/errors.test.js
- test/i18n/global.provider.test.js
- test/injection/config.test.js
- test/plugins/GlobalErrorPlugin.test.js
- test/service/StoreService.test.js
- webpack.config.js
First use case: inform the user about unavailable GeoResources
> add global error handling

- src/services/MapService.js
- test/service/MapService.test.js
This PR gives the `MapService` two high-level methods for length and area calculation based on  an array of coordinates.
The MapService detects which kind of calculation is needed and does all the necessary transformation of the coordinates.
Then it calls the low-level methods of the `OlCoordinateService`. For `getLength` its implementation could be:
```
/**
* Calculates the length of an array of coordinates.
*
* The kind of calculations depends on the  `geodesic` parameter:
* When `geodesic` is set to `true`, the coordinates must be either in 4326 or 3857 and calculation is done in a geodesic manner.
* When `geodesic` is set to `false`, the coordinates must be transformed in a projected SRID before and calculation is done on a projected plane.
*
*
* @param …
```
> MapService: add calcArea() and calcLength()

- src/modules/routing/components/waypoints/waypointItem.css
- test/modules/routing/components/WaypointItem.test.js
> WaypointItem: adjust WaypointButtons

- src/plugins/GlobalErrorPlugin.js
- test/plugins/GlobalErrorPlugin.test.js
> GlobalErrorPlugin: throttle firing of generic notification

- src/modules/elevationProfile/i18n/elevationProfile.provider.js
- test/modules/elevationProfile/i18n/elevationProfile.provider.test.js
> ElevationProfile: update  i18n

- src/modules/search/components/menu/types/geoResource/GeoResourceResultItem.js
- src/plugins/AuthPlugin.js
- src/services/GeoResourceService.js
- test/modules/search/components/menu/types/geoResource/GeoResourceResultItem.test.js
- test/plugins/AuthPlugin.test.js
- test/service/GeoResourceService.test.js
> GeoResourceResultItem: support GeoResource roles

- src/modules/olMap/services/StyleService.js
- test/modules/olMap/services/StyleService.test.js
fixes #2294
fix _addMarkerStyle for features without a textStyle
> StyleService: addMarkerStyle

- src/modules/topics/components/menu/catalog/CatalogLeaf.js
- src/store/layers/layers.action.js
- test/modules/topics/components/menu/catalog/CatalogLeaf.test.js
- test/store/layers/layers.reducer.test.js
> CatalogLeaf: layer must be addressed by its GeoResource id

- package-lock.json
- package.json
FF124 seems to cause flaky tests more frequent
> downgrade playwright from 1.43.0 to 1.42.1

- src/modules/olMap/handler/elevationProfile/OlElevationProfileHandler.js
- test/modules/olMap/handler/elevationProfile/OlElevationProfileHandler.test.js
> OlElevationProfileHandler: update store on deselect

- src/modules/olMap/utils/olLoadFunction.provider.js
- test/modules/olMap/util/olLoadFunction.provider.test.js
- test/plugins/GlobalErrorPlugin.test.js
> handle DomException caused by timeout

- src/plugins/RoutingPlugin.js
- test/plugins/RoutingPlugin.test.js
> do not close  the elevation profile unnecessarily

- src/chunks/public-web-component.js
- src/main.css
- src/modules/public/components/PublicComponent.js
- src/modules/public/components/publicComponent.css
- src/wcWrapper.html
- test/modules/public/components/PublicComponent.test.js
> public WC: rework style setup

- src/modules/olMap/handler/draw/OlDrawHandler.js
- src/modules/olMap/handler/measure/OlMeasurementHandler.js
- src/modules/olMap/overlayStyle/MeasurementOverlayStyle.js
- test/modules/olMap/handler/draw/OlDrawHandler.test.js
- test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
- test/modules/olMap/overlayStyle/MeasurementOverlayStyle.test.js
fix handling of dragPan interaction while dragging an overlay
> MeasurementOverlayStyle: handle pointerup event on map once while dragging overlay

- src/modules/chips/components/chipsContainer/chipsContainer.css
- src/modules/header/components/header.css
- src/modules/menu/components/navigationRail/navigationRail.css
> fixes z-index and pointer-events

- src/services/EnvironmentService.js
- test/service/EnvironmentService.test.js
and remove obsolete `isTouchWithMouseSupport()`
> fix touch device detection

- bundlesize.config.json
- src/chunks/public-web-component.js
- src/embedWrapper.html
- src/plugins/EncodeStatePlugin.js
- src/plugins/GlobalErrorPlugin.js
- src/services/ShareService.js
- src/wc.js
- test/e2e/embed.page.spec.js
- test/plugins/EncodeStatePlugin.test.js
- test/plugins/GlobalErrorPlugin.test.js
- test/service/ShareService.test.js
> optimize WC

- src/modules/chips/components/chipsContainer/chipsContainer.css
> fix chips z-index for portrait mode

- src/modules/footer/components/Footer.js
- test/modules/footer/components/Footer.test.js
> Add isEmbedded check to Footer

- src/modules/olMap/utils/olStyleUtils.js
- test/modules/olMap/util/olStyleUtils.test.js
> olStyleUtils: fix font-family name for default-font

- src/modules/topics/components/menu/assets/arrowTopRightShort.svg
- src/modules/topics/components/menu/catalog/CatalogNode.js
- src/modules/topics/components/menu/catalog/catalogNode.css
- test/modules/topics/components/menu/catalog/CatalogNode.test.js
> add tree like style to CatalogNode

- src/modules/featureInfo/components/featureInfoIframePanel/featureInfoIframePanel.css
- src/modules/featureInfo/components/featureInfoPanel/featureInfoPanel.css
add CSS classes:
. button
. primary
. secondary
> Add button style to Objekt-Info

- src/i18n/global.provider.js
- src/modules/olMap/handler/routing/OlRoutingHandler.js
- test/i18n/global.provider.test.js
- test/modules/olMap/handler/routing/OlRoutingHandler.test.js
- Labels of permanent layer
- Label of imported KML
> Routing: improve labels

- src/modules/menu/components/mainMenu/mainMenu.css
- test/modules/menu/components/mainMenu/MainMenu.test.js
> Fix full sized menu overflow 45104559

- src/modules/routing/components/routeDetails/RouteChart.js
- src/services/RoutingService.js
- test/modules/routing/components/RouteChart.test.js
- test/modules/routing/components/RouteDetails.test.js
- test/service/RoutingService.test.js
- test/service/provider/chartItemStyles.provider.test.js
- optimize display of route segment type 'unknown'
- fix formatting of distance values in chart tooltip
> RouteChart: optimize display of route segment type 'unknown' [Ticket#45104573,#45104574]

- src/modules/chips/components/assistChips/ShareDataChip.js
- test/modules/chips/components/ShareDataChip.test.js
> v4.2: sharing user generated data: always disable possible active tool

- src/modules/chips/components/assistChips/ShareDataChip.js
- test/modules/chips/components/ShareDataChip.test.js
> sharing user generated data: always disable possible active tool

- src/services/MapService.js
- test/service/MapService.test.js
> v4.2: restore UTM 33  in context menu

- src/services/MapService.js
- test/service/MapService.test.js
> restore UTM 33 in context menu

- src/services/ShareService.js
- src/store/highlight/highlight.reducer.js
- test/service/ShareService.test.js
> encode highlight feature

- src/modules/olMap/formats/kml.js
- src/modules/olMap/handler/draw/OlDrawHandler.js
- src/modules/olMap/handler/measure/OlMeasurementHandler.js
- test/modules/olMap/handler/draw/OlDrawHandler.test.js
- test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
> rework file storage: adjust ol handler

- src/modules/olMap/utils/olLoadFunction.provider.js
- src/plugins/GlobalErrorPlugin.js
- test/modules/olMap/util/olLoadFunction.provider.test.js
- test/plugins/GlobalErrorPlugin.test.js
* BvvBaaImageLoadFunction: increase timeout
* remove layer only when GeoResource requires authentication
> increase WMS timeout and finetune error handling

- src/modules/map/components/contextMenu/MapContextMenuContent.js
- src/modules/map/i18n/contextMenu.provider.js
- src/services/AdministrationService.js
- src/services/provider/administration.provider.js
- test/modules/map/components/contextMenu/MapContextMenuContent.test.js
- test/modules/map/i18n/contextMenu.provider.test.js
- test/service/provider/administration.provider.test.js
> ContextMenu: display parcel number when available 

- src/modules/map/components/contextMenu/MapContextMenuContent.js
- src/modules/map/i18n/contextMenu.provider.js
- src/services/AdministrationService.js
- src/services/provider/administration.provider.js
- test/modules/map/components/contextMenu/MapContextMenuContent.test.js
- test/modules/map/i18n/contextMenu.provider.test.js
- test/service/provider/administration.provider.test.js
display parcel number when available
> v4.2: ContextMenu - display parcel number when available

- src/modules/olMap/handler/draw/OlDrawHandler.js
- src/modules/olMap/handler/measure/OlMeasurementHandler.js
- test/modules/olMap/handler/draw/OlDrawHandler.test.js
- test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
> OlLayerHandlers: fix handling of draw layer on copy/clone

- src/modules/iframe/components/generator/IframeGenerator.js
- test/modules/iframe/components/IframeGenerator.test.js
> Change start value in portrait mode

- src/plugins/TimeTravelPlugin.js
- test/plugins/TimeTravelPlugin.test.js
Set the timeTravel active property to false when die BottomSheet could not be opened
> TimeTravelPlugin:  Set the timeTravel active property to false when die BottomSheet could not be opened

- src/modules/stackables/components/notificationItem/NotificationItem.js
- src/services/SecurityService.js
- test/modules/stackables/components/NotificationItem.test.js
- test/modules/stackables/components/StackableContentPanel.test.js
> update NotificationItem with sanitized content

- src/modules/layerManager/components/layerItem.css
- src/modules/menu/components/mainMenu/content/abstractMvuContentPanel.css
- src/modules/mvuElement.css
> Fix layerItem layout

- src/modules/stackables/components/bottomSheet/BottomSheet.js
- test/modules/stackables/components/BottomSheet.test.js
> BottomSheet: fix fadeout behavior on dismiss

- src/store/navigationRail/navigationRail.reducer.js
- test/store/navigationRail/navigationRail.reducer.test.js
> set NavRail initially open in landscape orientation

- src/modules/olMap/components/olMap.css
> Add zoom rectangle style

- src/modules/elevationProfile/components/panel/ElevationProfile.js
- test/modules/elevationProfile/components/panel/ElevationProfile.test.js
> ElevationProfile: Fix tooltip distance value

- src/modules/stackables/components/bottomSheet/bottomSheet.css
- src/modules/timeTravel/components/TimeTravelSlider.js
> Fix slider layout

- src/modules/olMap/utils/olStyleUtils.js
- test/modules/olMap/util/olStyleUtils.test.js
> rework offset for text on marker

- src/modules/olMap/services/Mfp3Encoder.js
- test/modules/olMap/formats/Mfp3Encoder.test.js
translate labelOffsetY due to changes on marker styles
> Mfp3Encoder: update labelOffsetY

- src/modules/header/components/Header.js
- src/modules/header/components/header.css
- src/modules/toolbox/components/toolBar/toolBar.css
> Hide empty badge

- src/modules/timeTravel/i18n/timeTravel.provider.js
- test/modules/timeTravel/i18n/timetravel.provider.test.js
> Fix tooltip text #45108037

- src/modules/olMap/handler/measure/OlMeasurementHandler.js
- test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
... while feature changes in modify interaction
> OlMeasurementHandler: update projectedLength property

- src/modules/olMap/services/StyleService.js
- test/modules/olMap/services/StyleService.test.js
> StyleService: extend defaultStyle handling for GPX

- src/modules/olMap/utils/olLoadFunction.provider.js
- test/modules/olMap/util/olLoadFunction.provider.test.js
> bvvTileLoadFunction: prevent memory leak and avoid requests of "undefined"

- src/modules/chips/components/assistChips/ShareDataChip.js
- src/modules/olMap/services/Mfp3Encoder.js
- src/modules/toolbox/components/shareToolContent/ShareToolContent.js
- src/utils/urlUtils.js
- test/modules/chips/components/ShareDataChip.test.js
- test/modules/olMap/formats/Mfp3Encoder.test.js
- test/modules/toolbox/components/shareToolContent/ShareToolContent.test.js
- test/utils/urlUtils.test.js
remove a query parameter when its value is null
> extend urlUtils

- src/modules/olMap/services/Mfp3Encoder.js
- test/modules/olMap/formats/Mfp3Encoder.test.js
> v4.3: Mfp3Encoder: update sort order

- src/modules/olMap/components/OlMap.js
- test/modules/olMap/components/OlMap.test.js
> pan map on pressing mouse wheel

- src/modules/olMap/tooltip/HelpTooltip.js
- test/modules/olMap/tooltip/HelpTooltip.test.js
...for better readability of distance overlay (#2761)
> HelpTooltip v4.3: positioning from center-left to top-left 

- src/modules/commons/components/spinner/Spinner.js
- src/modules/commons/components/valueSelect/ValueSelect.js
- src/modules/commons/i18n/spinner.provider.js
- src/modules/commons/i18n/valueSelect.provider.js
- test/modules/commons/components/Spinner.test.js
- test/modules/commons/i18n/spinner.provider.test.js
- test/modules/commons/i18n/valueSelect.provider.test.js
> Commons: update i18n keys

- src/i18n/global.provider.js
- src/modules/menu/components/mainMenu/content/misc/BvvMiscContentPanel.js
- src/modules/olMap/handler/draw/OlDrawHandler.js
- src/modules/olMap/handler/measure/OlMeasurementHandler.js
- src/modules/olMap/i18n/olMap.provider.js
- src/modules/toolbox/components/shareToolContent/ShareToolContent.js
- src/modules/toolbox/i18n/toolbox.provider.js
- test/i18n/global.provider.test.js
- test/modules/menu/components/mainMenu/content/more/BvvMiscContentPanel.test.js
- test/modules/olMap/handler/draw/OlDrawHandler.test.js
- test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
- test/modules/olMap/i18n/olMap.provider.test.js
- test/modules/toolbox/components/shareToolContent/ShareToolContent.test.js
- test/modules/toolbox/i18n/toolbox.provider.test.js
and refactored code using a unique key
> update terms of use

- src/modules/olMap/handler/measure/OlMeasurementHandler.js
- test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
> OlMeasurementHandler: update PROJECTED_LENGTH_GEOMETRY_PROPERTY of old features onChange

- src/modules/olMap/services/StyleService.js
- test/modules/olMap/services/StyleService.test.js
* use default-style if text style is missing
* use default-style if image style is missing
> StyleService:  handle text feature with empty text style

- src/modules/olMap/services/Mfp3Encoder.js
- test/modules/olMap/formats/Mfp3Encoder.test.js
update behavior for advanced feature styles handling geodesic azimuth circle
> Mfp3Encoder: fix handling geodesic azimuth circle

- src/plugins/MainMenuPlugin.js
- test/plugins/MainMenuPlugin.test.js
> exclude TabIds.ROUTING from handling (v4.3)

- src/main.css
- src/modules/header/components/header.css
> Add style for super small devices

- src/modules/olMap/services/VectorLayerService.js
- test/modules/olMap/services/VectorLayerService.test.js
> VectorLayerService: fix  _updateStyle() when only hidden layers are present (v4.3)

- src/modules/olMap/services/VectorLayerService.js
- test/modules/olMap/services/VectorLayerService.test.js
> VectorLayerService: fix  _updateStyle() when only hidden layers are present

- src/modules/olMap/components/OlMap.js
- test/modules/olMap/components/OlMap.test.js
> OlMap: avoid fit on empyt extent (v4.3)

- src/modules/olMap/handler/draw/OlDrawHandler.js
- src/modules/olMap/handler/measure/OlMeasurementHandler.js
- src/services/FileStorageService.js
- test/service/FileStorageService.test.js
* increase POST timeout to 10s
* remove early save after reading rocksi features
---------
> optimize file storage handling

- src/modules/olMap/components/OlMap.js
- test/modules/olMap/components/OlMap.test.js
> avoid fit on empty extent

- src/modules/olMap/handler/draw/OlDrawHandler.js
- src/modules/olMap/handler/measure/OlMeasurementHandler.js
- test/modules/olMap/handler/draw/OlDrawHandler.test.js
- test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
revert remove of early save after reading rocksi features (#2852)
> OlMapHandlers: Fix early save

- src/modules/chips/components/assistChips/ShareChip.js
- src/modules/chips/i18n/chips.provider.js
- test/modules/chips/components/ShareChip.test.js
- test/modules/chips/i18n/chips.provider.test.js
> ShareChip: add label setter

- src/modules/olMap/services/StyleService.js
- test/modules/olMap/services/StyleService.test.js
> StyleService: update measurement style on changed resolution

- src/modules/layerManager/components/layerItem.css
> Fix LayerItem bar z-index

- src/domain/geometryStatisticTypeDef.js
- src/domain/geometryTypes.js
- src/modules/olMap/handler/measure/OlMeasurementHandler.js
- src/modules/toolbox/components/measureToolContent/MeasureToolContent.js
- src/store/measurement/measurement.reducer.js
- test/domain/geometryTypes.test.js
- test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
- test/modules/toolbox/components/measureToolContent/MeasureToolContent.test.js
- test/store/measurement/measurement.reducer.test.js
> MeasureToolContent: handle empty statistic

- src/modules/chips/components/assistChips/ShareChip.js
- src/modules/share/components/dialog/ShareDialogContent.js
- test/modules/chips/components/ShareChip.test.js
- test/modules/share/components/shareDialogContent/ShareDialogContent.test.js
- test/modules/toolbox/components/shareToolContent/ShareToolContent.test.js
> avoid unnecessary warning messages when sharing is canceled

- src/modules/geoResourceInfo/services/provider/geoResourceInfoResult.provider.js
- src/services/HttpService.js
- src/services/ImportVectorDataService.js
- src/services/provider/feedback.provider.js
- src/services/provider/geoResource.provider.js
- src/services/provider/profile.provider.js
- src/services/provider/route.provider.js
- src/services/provider/sourceType.provider.js
- src/services/provider/wmsCapabilities.provider.js
- test/domain/geoResources.test.js
- test/modules/geoResourceInfo/services/provider/geoResourceInfoResult.provider.test.js
- test/service/HttpService.test.js
- test/service/ImportVectorDataService.test.js
- test/service/provider/feedback.provider.test.js
- test/service/provider/geoResource.provider.test.js
- test/service/provider/profile.provider.test.js
- test/service/provider/route.provider.test.js
- test/service/provider/sourceType.provider.test.js
- test/service/provider/wmsCapabilities.provider.test.js
* increase default timeout from 1s to 10s
* remove timeouts where appropriate  and < 10s
* make prettier happy
> HttpService: increase default timeout

- src/modules/olMap/handler/draw/OlDrawHandler.js
- src/modules/olMap/handler/measure/OlMeasurementHandler.js
- test/modules/olMap/handler/draw/OlDrawHandler.test.js
- test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
> OlMapHandlers: track fileId to handle unchanged content

- src/modules/olMap/handler/draw/OlDrawHandler.js
- src/modules/olMap/handler/measure/OlMeasurementHandler.js
- test/modules/olMap/handler/draw/OlDrawHandler.test.js
- test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
* add storeId to handle unchanged content
> OlMapHandlers: track fileId to handle unchanged content (4.3)

- src/modules/info/components/coordinateInfo/coordinateinfo.css
- src/modules/info/components/geometryInfo/geometryInfo.css
- src/modules/info/i18n/geometryInfo.provider.js
- src/modules/toolbox/components/drawToolContent/DrawToolContent.js
- test/modules/info/i18n/geometryInfo.provider.test.js
- test/modules/toolbox/components/drawToolContent/DrawToolContent.test.js
> CoordinateInfo: optimize UI

- src/modules/stackables/components/notificationItem/NotificationItem.js
- src/modules/stackables/components/notificationItem/notificationItem.css
- test/modules/stackables/components/NotificationItem.test.js
fix: #2500
- click to close
- remove header
- add title
- increase font-size
> make notification item removeable by the user

- src/modules/chips/components/assistChips/AbstractAssistChip.js
- src/modules/chips/components/assistChips/ElevationProfileChip.js
- src/modules/chips/components/assistChips/ExportVectorDataChip.js
- src/modules/chips/components/assistChips/MapFeedbackChip.js
- src/modules/chips/components/assistChips/RoutingChip.js
- src/modules/chips/components/assistChips/ShareChip.js
- src/modules/chips/components/assistChips/ShareDataChip.js
- src/modules/chips/i18n/chips.provider.js
- test/modules/chips/components/AbstractAssistChip.test.js
- test/modules/chips/components/ElevationProfileChip.test.js
- test/modules/chips/components/ExportVectorDataChip.test.js
- test/modules/chips/components/MapFeedbackChip.test.js
- test/modules/chips/components/RoutingChip.test.js
- test/modules/chips/components/ShareChip.test.js
- test/modules/chips/components/ShareDataChip.test.js
- test/modules/chips/i18n/chips.provider.test.js
> AbstractAssistChip: add property for a optional title value

- src/modules/chips/components/chipsContainer/chipsContainer.css
- src/modules/footer/components/footer.css
- src/modules/stackables/components/bottomSheet/bottomSheet.css
> fix gaps footer and bottomSheet

- src/modules/commons/components/button/Button.js
- test/modules/commons/components/Button.test.js
> BaButton: add title property

- src/domain/geoResources.js
- src/plugins/BeforeUnloadPlugin.js
- src/plugins/FeatureCollectionPlugin.js
- src/plugins/ImportPlugin.js
- src/services/GeoResourceService.js
- src/services/ImportVectorDataService.js
- test/domain/geoResources.test.js
- test/plugins/BeforeUnloadPlugin.test.js
- test/plugins/FeatureCollectionPlugin.test.js
- test/plugins/ImportPlugin.test.js
- test/service/GeoResourceService.test.js
- test/service/ImportVectorDataService.test.js
> warn before page unload when local data are present

- src/modules/search/components/menu/types/cp/CpResultItem.js
- src/modules/search/services/domain/searchResult.js
- src/modules/search/services/provider/searchResult.provider.js
- test/modules/search/components/menu/types/cp/CpResultItem.test.js
- test/modules/search/services/domain/searchResult.test.js
- test/modules/search/services/provider/searchResult.provider.test.js
`CadastralParcelSearchResult ` should contain a `Geometry`
> refactor CadastralParcelSearchResult

- src/domain/geometry.js
- src/modules/elevationProfile/components/panel/ElevationProfile.js
- src/modules/featureInfo/components/featureInfoIframePanel/FeatureInfoIframePanel.js
- src/modules/featureInfo/components/featureInfoPanel/FeatureInfoPanel.js
- src/modules/olMap/handler/featureInfo/featureInfoItem.provider.js
- src/modules/olMap/handler/highlight/OlHighlightLayerHandler.js
- src/modules/search/components/menu/types/cp/CpResultItem.js
- src/modules/search/components/menu/types/location/LocationResultItem.js
- src/plugins/ContextClickPlugin.js
- src/plugins/HighlightPlugin.js
- src/plugins/RoutingPlugin.js
- src/services/SourceTypeService.js
- src/store/highlight/highlight.action.js
- test/domain/feature.test.js
- test/domain/geometry.test.js
- test/modules/elevationProfile/components/panel/ElevationProfile.test.js
- test/modules/featureInfo/components/FeatureCollectionPanel.test.js
- test/modules/featureInfo/components/FeatureInfoIframePanel.test.js
- test/modules/featureInfo/components/FeatureInfoPanel.test.js
- test/modules/olMap/handler/featureInfo/featureInfoItem.provider.test.js
- test/modules/olMap/handler/highlight/OlHighlightLayerHandler.test.js
- test/modules/search/components/menu/types/cp/CpResultItem.test.js
- test/modules/search/components/menu/types/location/LocationResultItem.test.js
- test/plugins/ContextClickPlugin.test.js
- test/plugins/FeatureCollectionPlugin.test.js
- test/plugins/HighlightPlugin.test.js
- test/plugins/RoutingPlugin.test.js
- test/service/SourceTypeService.test.js
- test/store/highlight/highlight.action.test.js
- test/store/highlight/highlight.reducer.test.js
The `HighlightFeature ` should contain a `Geometry` or a `Coordinate`
> refactor the HighlightFeature

- src/modules/layerManager/components/layerManager.css
> Layermanager button direction

- src/modules/search/components/menu/types/location/locationResultItem.css
> Min-height searchitem

- src/services/provider/units.provider.js
- test/service/provider/units.provider.test.js
distance < 1km: 1 fraction digit
distance > 1km: 2 fraction digits
> Units: update bvv distance formatting

- src/services/provider/units.provider.js
- test/service/provider/units.provider.test.js
distance < 1km: 1 fraction digit
distance > 1km: 2 fraction digits
> Units: update bvv distance formatting (4.3)

- src/modules/olMap/handler/measure/OlMeasurementHandler.js
- src/modules/olMap/overlayStyle/MeasurementOverlayStyle.js
- src/modules/olMap/services/OverlayService.js
- src/modules/olMap/services/StyleService.js
- test/modules/olMap/handler/measure/OlMeasurementHandler.test.js
- test/modules/olMap/overlayStyle/MeasurementOverlayStyle.test.js
- test/modules/olMap/services/OverlayService.test.js
- test/modules/olMap/services/StyleService.test.js
> MeasurementOverlayStyle: handle map listener correctly

- src/modules/layerManager/components/layerItem.css
> Fix margin of the time travel layer item

- src/modules/share/i18n/share.provider.js
- src/services/GeoResourceService.js
- src/services/HttpService.js
- src/services/provider/auth.provider.js
- src/store/auth/auth.reducer.js
- test/modules/share/i18n/share.provider.test.js
- test/service/GeoResourceService.test.js
- test/service/HttpService.test.js
- test/service/provider/auth.provider.test.js
We show the Sign-In dialog and do a retry of the intercepted requests
> handle authorization downgrade

- src/modules/menu/components/navigationRail/navigationRail.css
> No sub buttons for super small screens

- src/plugins/MainMenuPlugin.js
- test/plugins/MainMenuPlugin.test.js
> Routing UI: do not open tray in portrait mode automatically

- src/modules/menu/components/navigationRail/navigationRail.css
> NavigationRail style fix

- src/modules/header/components/header.css
- src/modules/mvuElement.css
> Fix input -webkit-autofill colors

- src/modules/chips/components/chipsContainer/chipsContainer.css
> Fix chips container z-index

- src/plugins/HighlightPlugin.js
- test/plugins/HighlightPlugin.test.js
> HighlightPlugin: clear search result related highlight items again

- src/modules/chips/components/chipsContainer/chipsContainer.css
> Remove scrollbar artefact

- src/i18n/global.provider.js
- src/modules/map/components/geolocationButton/GeolocationButton.js
- src/modules/map/components/geolocationButton/geolocationButton.css
- src/modules/map/i18n/geolocationButton.provider.js
- test/i18n/global.provider.test.js
- test/modules/map/components/geolocationButton/GeolocationButton.test.js
- test/modules/map/i18n/geolocationButton.provider.test.js
> optimize geolocation

- src/modules/menu/components/navigationRail/navigationRail.css
> Fix icon cut off

- src/plugins/TopicsPlugin.js
- test/plugins/TopicsPlugin.test.js
> TopicsPlugin: remove setting the default topic

- src/modules/baseLayer/components/container/BaseLayerContainer.js
- test/modules/baseLayer/components/BaseLayerContainer.test.js
> BaseLayerContainer: ensure categories are always loaded

- src/modules/olMap/utils/olGeometryUtils.js
- src/modules/olMap/utils/olStyleUtils.js
- test/modules/olMap/handler/elevationProfile/OlElevationProfileHandler.test.js
- test/modules/olMap/util/olGeometryUtils.test.js
- test/modules/olMap/util/olStyleUtils.test.js
> Measurement: polygon orientation in digitize order

- src/modules/menu/components/mainMenu/content/misc/BvvMiscContentPanel.js
- src/modules/menu/components/mainMenu/content/misc/bvvMiscContentPanel.css
- test/modules/menu/components/mainMenu/content/more/BvvMiscContentPanel.test.js
> Fix portrait miscPanel toggle font-size

- src/domain/geoResources.js
- src/modules/olMap/services/VectorLayerService.js
- src/modules/olMap/utils/olLoadFunction.provider.js
- src/services/provider/geoResource.provider.js
- src/store/layers/layers.action.js
- src/store/layers/layers.reducer.js
- test/domain/geoResources.test.js
- test/modules/olMap/services/VectorLayerService.test.js
- test/modules/olMap/util/olLoadFunction.provider.test.js
- test/service/provider/geoResource.provider.test.js
- test/store/layers/layers.action.test.js
- test/store/layers/layers.reducer.test.js
> improve OAF support

- src/modules/header/components/Header.js
- src/modules/search/components/menu/SearchResultsPanel.js
- src/modules/search/components/menu/types/cp/CpResultItem.js
- src/modules/search/components/menu/types/cp/cpResultsPanel.css
- src/modules/search/components/menu/types/geoResource/GeoResourceResultItem.js
- src/modules/search/components/menu/types/geoResource/geoResourceResultsPanel.css
- src/modules/search/components/menu/types/location/LocationResultItem.js
- src/modules/search/components/menu/types/location/locationResultsPanel.css
- test/modules/header/components/Header.test.js
- test/modules/search/components/menu/SearchResultsPanel.test.js
* remove focus and blur
* add style
* add: scroll into view
add: set cursor
* sets the input cursor only if no search result exists
* add test
* add display block for FireFox scrollIntoView
* change Mouse and keyboard  highlighting
* clean code
* update key handling, preventing actions when shiftKey is active
* typo
* refactor scrollToView handling, update test
* add box-shadow:
---------
> v4.4: Search keybord navigation optimization (#3108)

- src/modules/olMap/formats/kml.js
- src/modules/olMap/handler/routing/OlRoutingHandler.js
- test/modules/olMap/formats/kml.test.js
- test/modules/olMap/handler/routing/OlRoutingHandler.test.js
update timing of routerendering
> v4.4 RoutingStyle: prevent rendering of large icons (#3113) 

- src/modules/layerManager/components/LayerItem.js
- src/store/bottomSheet/bottomSheet.action.js
- src/store/bottomSheet/bottomSheet.reducer.js
- test/modules/layerManager/components/LayerItem.test.js
- test/modules/layerManager/components/LayerManager.test.js
> LayerItem: improve handling of settings sheet

- src/chunks/public-web-component.js
- src/embed.js
> add missing module `info` for embed and wc

- src/modules/featureInfo/components/featureInfoPanel/featureInfoPanel.css
- src/modules/olMap/handler/featureInfo/featureInfoItem.provider.js
- test/modules/olMap/handler/featureInfo/featureInfoItem.provider.test.js
> Properties style and visibility toggle 

- src/modules/olMap/services/VectorLayerService.js
- src/modules/olMap/utils/olLoadFunction.provider.js
- test/modules/olMap/services/VectorLayerService.test.js
- test/modules/olMap/util/olLoadFunction.provider.test.js
- handle optional OAF response properties `numberReturned` and `numberMatched`
- limit OAF request via debounce
> optimize OAF loading

- src/modules/oaf/components/OafMask.js
- test/modules/oaf/components/OafFilter.test.js
- test/modules/oaf/components/OafFilterGroup.test.js
- test/modules/oaf/components/OafMask.test.js
> Fix OafMask overrides filter of wrong layer

- src/modules/oaf/components/OafFilterGroup.js
- src/modules/oaf/components/OafMask.js
- src/modules/oaf/components/oafFilter.css
- src/modules/oaf/components/oafMask.css
- test/modules/oaf/components/OafFilterGroup.test.js
- test/modules/oaf/components/OafMask.test.js
> oaf mobile UI

- src/i18n/global.provider.js
- src/services/GeoResourceService.js
- src/services/provider/geoResourceKeyword.provider.js
- test/i18n/global.provider.test.js
- test/service/GeoResourceService.test.js
- test/service/provider/geoResourceKeyword.provider.test.js
> add a keyword provider for GeoResources
